import type { Locale } from "./preferences";

// Server actions return stable Arabic copy; keep the same feedback in either UI language.
const english: Record<string, string> = {
  "تم حفظ التغيير.": "Changes saved.",
  "تم حفظ نسخة ثابتة من البيانات والملف.": "A fixed copy of the data and file was saved.",
  "تم التراجع عن الطلبات التي لم تتغير بعد العملية؛ التغييرات اللاحقة محفوظة.": "Unchanged applications were restored. Later changes were preserved.",
  "تم حفظ خيارات الملف المهاري والخصوصية.": "Talent profile and privacy settings saved.",
  "تم إنهاء صلاحية المشرف العام.": "Super Admin access ended.",
  "تم تحديث حالة الجهة.": "Organization status updated.",
  "تم تحديث حالة اللجنة.": "Committee status updated.",
  "تم تعيين القائد الأساسي وحفظ تاريخ الأدوار.": "Primary leader appointed and role history saved.",
  "تم حفظ الإعلان.": "Announcement saved.",
  "تم حفظ اللجنة.": "Committee saved.",
  "تم حفظ بيانات الجهة.": "Organization details saved.",
  "تم منح صلاحية المشرف العام.": "Super Admin access granted.",
  "تم نسخ بيانات اللجنة بدون أعضاء أو أدوار.": "Committee details copied without members or roles.",
  "تمت أرشفة الإعلان.": "Announcement archived.",
  "تأكد من البريد الإلكتروني وحاول مرة ثانية.": "Check the email address and try again.",
  "تسجيل الدخول غير متاح الآن. حاول لاحقًا.": "Sign-in is unavailable now. Please try later.",
  "وصلت حد طلب الرسائل. انتظر قليلًا قبل المحاولة مرة ثانية.": "You reached the message request limit. Wait a while before trying again.",
  "تعذّر إرسال البريد لهذا العنوان. راجع إعداد مرسل البريد في المشروع.": "Email could not be sent to this address. Check the project's email sender settings.",
  "تعذّر إرسال الرسالة الآن. حاول بعد قليل.": "The message could not be sent now. Try again shortly.",
  "أدخل رمز التحقق المكوّن من 6 أرقام.": "Enter the 6-digit verification code.",
  "الرمز غير صحيح أو انتهت صلاحيته. تحقق منه أو اطلب رمزًا جديدًا.": "The code is incorrect or expired. Check it or request a new one.",
  "تعذّر التحقق الآن. حاول بعد قليل.": "Verification is unavailable now. Try again shortly.",
  "حفظ البيانات غير متاح الآن. حاول لاحقًا.": "Saving details is unavailable now. Try again later.",
  "راجع الحقول الموضحة وأكمل البيانات.": "Review the highlighted fields and complete your details.",
  "تعذّر حفظ البيانات. تأكد من صحة بياناتك وحاول بعد قليل.": "Details could not be saved. Check your information and try again shortly.",
  "تعذّر حفظ التغيير. راجع الحقول والصلاحيات؛ حدّث الصفحة إذا تغيرت المهمة أو المشاركة. رفض التسليم يحتاج ملاحظة؛ اعتماد المهمة يحتاج فصلًا أكاديميًا يغطي تاريخ الاعتماد.": "Changes could not be saved. Check fields and permissions, and refresh if the task or participation changed. Rejecting a submission requires a note; approving hours requires an academic term covering the approval date.",
  "تعذّر حفظ التغيير. راجع الحقول، الفصل الأكاديمي والصلاحيات، وحدّث الصفحة إذا تغير السجل. الرفض والإبطال يحتاجان سببًا.": "Changes could not be saved. Check fields, academic term and permissions, and refresh if the record changed. Rejection and voiding require a reason.",
  "تعذّر حفظ التغيير. راجع الحقول والصلاحيات وحدّث الصفحة. التسجيل له موعد وسعة؛ الإكمال يحتاج انتهاء الفعالية ومراجعة الحضور وفصلًا يغطي ساعات الأعضاء.": "Changes could not be saved. Check fields and permissions, then refresh. Registration has dates and capacity; completion requires the event to end, attendance review and an academic term covering member hours.",
  "تعذّر الحفظ. راجع الحقول والصلاحيات؛ حدّث الصفحة إذا تغيّرت نسخة النموذج أو حالة الطلب. رسالة المقابلة مطلوبة عند اختيار مقابلة.": "Changes could not be saved. Check fields and permissions, and refresh if the form version or application status changed. An interview decision requires a message.",
  "تعذّر إنشاء المستند أو حفظ التغيير. تحقق من النطاق والفترة والصلاحية ووجود ساعات معتمدة. قسّم الفترة إذا تجاوزت ٥٬٠٠٠ سجل.": "The document or change could not be saved. Check scope, period, permissions and approved hours. Split periods exceeding 5,000 records.",
  "حُفظت نسخة البيانات، لكن تعذّر تجهيز الملف في التخزين. افتح سجل المستندات وأعد تجهيز نفس النسخة؛ المحاولة المنقطعة تصبح قابلة للإعادة بعد ١٥ دقيقة.": "The data copy was saved, but file generation failed. Open document history and retry the same copy; an interrupted attempt can be retried after 15 minutes.",
  "تعذّر حفظ الملف المهاري. راجع الحقول؛ الروابط تبدأ بـ HTTPS، والإنجاز يحتاج نشاطًا معتمدًا تملكه داخل LUB.": "The talent profile could not be saved. Check fields; links must use HTTPS, and achievements require approved activities you own in LUB.",
  "أكمل بيانات حسابك وتأكد من أنه نشط قبل المتابعة.": "Complete your account details and make sure it is active before continuing.",
  "راجع بيانات النموذج وأكّد الإجراء إذا طُلب منك.": "Review the form and confirm the action if prompted.",
  "لا يمكن إنهاء صلاحية آخر مشرف عام نشط.": "The last active Super Admin cannot be removed.",
  "الحساب المحدد يحتاج التحقق من بريده وإكمال بياناته أولًا.": "The selected account must verify its email and complete its details first.",
  "تعذّر تنفيذ الإجراء. تحقق من صلاحياتك وصحة البيانات. عند تعيين حساب، يجب أن يكون متحققًا ومكتمل البيانات.": "The action could not be completed. Check your permissions and details. An appointed account must be verified and have complete details.",
  "أكّد الإجراء قبل المتابعة.": "Confirm the action before continuing.",
  "اكتب بريدًا صحيحًا للحساب المتحقق.": "Enter a valid email for the verified account.",
  "راجع هذا الحقل.": "Review this field.",
  "اكتب اسمًا من حرفين على الأقل.": "Enter a name of at least two characters.",
  "استخدم حروفًا إنجليزية صغيرة وأرقامًا، وافصل الكلمات بشرطة.": "Use lowercase English letters and digits, separated with hyphens.",
  "اختر عشرة مجالات على الأكثر.": "Choose no more than ten interests.",
  "اسم المجال بحد أقصى 40 حرفًا.": "An interest name can be at most 40 characters.",
  "اكتب رابط HTTPS صالحًا بدون بيانات دخول.": "Enter a valid HTTPS URL without login details.",
  "النبذة بحد أقصى 1000 حرف.": "The summary can be at most 1,000 characters.",
  "الرسالة بحد أقصى 3000 حرف.": "The mission can be at most 3,000 characters.",
  "انشر الإعلان قبل تثبيته.": "Publish the announcement before pinning it.",
  "اكتب سؤالًا من 3 إلى 500 حرف.": "Enter a question of 3 to 500 characters.",
  "وصل البحث إلى حد الطلبات. انتظر دقيقة ثم حاول مجددًا.": "Search reached its request limit. Wait a minute and try again.",
  "البحث غير متاح حاليًا.": "Search is currently unavailable.",
};

export function actionFeedback(message: string | undefined, locale: Locale): string | undefined {
  if (!message || locale === "ar") return message;
  return english[message] ?? message;
}
