import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import {notFound} from "next/navigation";
import {z} from "zod";
import {requireManagementUser} from "@/features/organizations/access";
import {taskWorkspace,listTasks} from "@/features/tasks/repository";
import {TaskFields} from "@/features/tasks/task-fields";
import {TaskForm} from "@/features/tasks/task-form";
import {TaskList,TaskPagination} from "@/features/tasks/task-list";
import {DateInput} from "@/features/forms/date-input";
import {getPreferences} from "@/lib/preferences";
export async function generateMetadata(){return localizedMetadata('إدارة المهام والقوالب','Tasks and templates');}
export default async function ManageTasksPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{page?:string;template?:string}>}){
 const [user,{locale}]=await Promise.all([requireManagementUser(),getPreferences()]);const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();const query=await searchParams;const page=z.coerce.number().int().min(0).max(10000).catch(0).parse(query.page??0);
 const [workspace,data]=await Promise.all([taskWorkspace(user.id,id),listTasks(user.id,{org:id,page})]);if(!workspace)notFound();const source=workspace.templates.find(t=>t.id===query.template&&t.is_active);const taskScopes=workspace.scopes.filter(s=>s.tasks),templateScopes=workspace.scopes.filter(s=>s.templates);
 const base=`/manage/organizations/${id}/tasks`;const allowedTemplate=(committee:string|null)=>templateScopes.some(s=>s.id===committee);
 const scopeField=(scopes:typeof workspace.scopes,value?:string|null)=><label>{c("نطاق العمل","Work scope")}<select name="committee" defaultValue={value??""}>{scopes.map(s=><option key={s.id??"organization"} value={s.id??""} dir="auto">{s.name}</option>)}</select></label>;
 return <div className="space-y-8"><div><Link className="text-link mb-5 inline-block" href={`/manage/organizations/${id}`}>{c("إعدادات الجهة","Organization settings")}</Link><h1 className="text-3xl leading-normal font-bold">{c("مهام","Tasks for")} <bdi>{workspace.name}</bdi></h1><p className="mt-3 leading-8 text-muted">{c("النشر والانضمام وتسليم المخرجات، بمراجعة مستقلة لكل مشارك.","Publish tasks, join and submit deliverables, with an independent review for each participant.")}</p></div>
 {taskScopes.length>0&&<section className="panel p-6"><h2 className="mb-5 text-xl font-semibold">{c("إنشاء مهمة","Create task")}</h2>{source&&<p className="mb-5 text-muted">{c("من القالب","From template")}: <bdi>{source.name}</bdi> · <Link className="text-link" href={base}>{c("ابدأ بدون قالب","Start without a template")}</Link></p>}<TaskForm key={source?.id??"blank"} operation="save-task" fields={{org:id,...(source?{template:source.id}:{})}} label={c("إنشاء مسودة المهمة","Create task draft")} locale={locale}>{scopeField(taskScopes,source?.committee_id)}<label>{c("قاعدة ساعات فعّالة (اختياري)","Active hours rule (optional)")}<select name="rule"><option value="">{c("استخدم الساعات المكتوبة أدناه","Use the hours entered below")}</option>{workspace.hourRules.filter(r=>!r.task_template_id||r.task_template_id===source?.id).map(r=><option key={r.id} value={r.id} dir="auto">{r.name} · {r.default_hours} {c("ساعة","hours")}</option>)}</select></label><p className="text-sm text-muted">{c("اختيار القاعدة يثبت ساعاتها عند إنشاء المهمة، بدل الرقم المكتوب.","Selecting a rule fixes its hours when creating the task instead of the value entered below.")}</p><TaskFields value={source?{title:source.name,description:source.description_template,default_hours:source.default_hours}:undefined} locale={locale}/></TaskForm></section>}
 <section aria-labelledby="tasks-title"><h2 id="tasks-title" className="mb-5 text-xl font-semibold">{c("المهام المتاحة","Available tasks")}</h2><TaskList items={data.items} locale={locale}/><TaskPagination page={page} more={data.more} base={base} locale={locale}/></section>
 <section className="space-y-5"><h2 className="text-xl font-semibold">{c("قوالب المهام","Task templates")}</h2>{workspace.templates.map(t=><article key={t.id} className="panel space-y-5 p-6"><h3 className="text-lg font-semibold"><bdi>{t.name}</bdi> · {t.is_active?c("نشط","Active"):c("مؤرشف","Archived")}</h3><p dir="auto" className="whitespace-pre-wrap break-words leading-8">{t.description_template}</p><p className="text-sm text-muted">{c("الساعات المقترحة","Suggested hours")}: {t.default_hours}</p>{t.is_active&&taskScopes.some(s=>t.committee_id===null||s.id===t.committee_id)&&<Link className="text-link inline-block" href={`${base}?template=${t.id}`}>{c("إنشاء مهمة من القالب","Create task from template")}</Link>}
 {allowedTemplate(t.committee_id)&&<details><summary className="cursor-pointer font-medium">{c("تعديل أو أرشفة القالب","Edit or archive template")}</summary><div className="mt-5"><TaskForm operation="template" fields={{org:id,template:t.id,committee:t.committee_id??"",revision:String(t.revision)}} label={c("حفظ القالب","Save template")} locale={locale}><TaskFields value={t} template locale={locale}/></TaskForm></div></details>}
 {allowedTemplate(t.committee_id)&&templateScopes.length>0&&<details><summary className="cursor-pointer font-medium">{c("نسخة مستقلة من القالب","Independent copy of template")}</summary><div className="mt-5"><TaskForm operation="template" fields={{org:id,source:t.id,description:"",hours:"0",active:"on"}} label={c("نسخ القالب","Copy template")} locale={locale}>{scopeField(templateScopes,t.committee_id)}<label>{c("اسم النسخة","Copy name")}<input name="title" required minLength={2} maxLength={120} defaultValue={`${t.name.slice(0,110)} (${c("نسخة","copy")})`}/></label></TaskForm></div></details>}</article>)}{!workspace.templates.length&&<p className="panel p-6 text-muted">{c("لا توجد قوالب متاحة ضمن صلاحياتك.","No templates are available under your permissions.")}</p>}
 {templateScopes.length>0&&<details className="panel p-6"><summary className="cursor-pointer font-medium">{c("إضافة قالب مهمة","Add task template")}</summary><div className="mt-5"><TaskForm operation="template" fields={{org:id}} label={c("إنشاء القالب","Create template")} locale={locale}>{scopeField(templateScopes)}<TaskFields template locale={locale}/></TaskForm></div></details>}</section>
 {workspace.canGrant&&<section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("تفويض صلاحيات المهام","Task permissions")}</h2><p className="text-sm leading-7 text-muted">{c("قائد الجهة ونائبه يديران مهام الجهة. قادة اللجان ونوابهم يديرون مهام لجنتهم تلقائيًا.","Organization leaders and deputies manage organization tasks. Committee leaders and deputies automatically manage their committee's tasks.")}</p>{workspace.members.length?<TaskForm operation="grant" fields={{org:id}} label={c("منح الصلاحية","Grant permission")} locale={locale}><label>{c("العضو","Member")}<select name="member">{workspace.members.map(m=><option key={m.id} value={m.id} dir="auto">{m.name}</option>)}</select></label><label>{c("الصلاحية","Permission")}<select name="capability"><option value="TASKS_MANAGE">{c("إدارة المهام ومراجعة المشاركات","Manage tasks and review participation")}</option><option value="TASK_TEMPLATES_MANAGE">{c("إدارة قوالب المهام","Manage task templates")}</option></select></label><label>{c("النطاق","Scope")}<select name="committee"><option value="">{c("الجهة بالكامل","Whole organization")}</option>{workspace.scopes.filter(s=>s.id).map(s=><option key={s.id} value={s.id!} dir="auto">{s.name}</option>)}</select></label><DateInput name="ends" label={c("انتهاء التفويض (اختياري)","Permission ends (optional)")} locale={locale}/></TaskForm>:<p>{c("لا يوجد أعضاء مؤهلون للتفويض.","No members are eligible for permission grants.")}</p>}
 {workspace.members.flatMap(m=>m.grants.map(g=><div key={g.id} className="border-t border-line pt-5"><p className="mb-4"><bdi>{m.name}</bdi> · {g.code==="TASKS_MANAGE"?c("إدارة المهام","Manage tasks"):c("إدارة القوالب","Manage templates")} · <bdi>{g.committee??c("الجهة بالكامل","Whole organization")}</bdi></p><TaskForm operation="end-grant" fields={{grant:g.id}} label={c("إنهاء التفويض","End permission")} locale={locale}/></div>))}</section>}</div>;
}
