import Link from "next/link";
import {DateInput} from "@/features/forms/date-input";
import {DocumentForm,PeriodFields} from "./form";
import type {DocumentItem,DocumentWorkspace} from "./repository";
import type {Locale} from "@/lib/preferences";
export function DocumentList({items,locale="ar"}:{items:DocumentItem[];locale?:Locale}){const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;const statuses:Record<string,string>=en?{Archived:"Archived",Ready:"Ready",Generating:"Generating file",Failed:"File generation failed"}:{Archived:"مؤرشف",Ready:"جاهز",Generating:"جارٍ تجهيز الملف",Failed:"تعذّر تجهيز الملف"};return items.length?<ul className="space-y-4">{items.slice(0,25).map(d=><li key={d.id} className="panel min-w-0 space-y-4 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="font-semibold break-words">{d.document_type_code==='Hours_Certificate'?c('بيان الساعات التطوعية','Volunteer hours certificate'):c('تقرير الساعات','Hours report')}</h2><span className="text-sm text-muted">{statuses[d.status_code]}</span></div><p dir="auto" className="break-words leading-7">{d.name} · {d.scope} · {d.period}</p><p className="text-sm leading-7 text-muted">{d.total} {c("ساعة معتمدة وقت الإصدار","approved hours at issue time")} · {new Intl.DateTimeFormat(en?'en-US':'ar-SA',{dateStyle:'medium',calendar:'gregory',timeZone:'Asia/Riyadh'}).format(new Date(d.generated_at))}</p>{['Ready','Archived'].includes(d.status_code)&&<div className="flex flex-wrap gap-3"><a href={`/documents/${d.id}/file`} className="button button-secondary">{d.document_type_code==='Hours_Certificate'?c('تنزيل بيان HTML','Download HTML certificate'):c('تنزيل تقرير CSV','Download CSV report')}</a>{d.document_type_code==='Hours_Certificate'&&<a href={`/documents/${d.id}/file?view=print`} target="_blank" rel="noopener noreferrer" className="button">{c("عرض البيان للطباعة","Print certificate")}</a>}</div>}{d.canRetry&&<DocumentForm operation="retry" fields={{document:d.id}} label={c("إعادة تجهيز نفس النسخة","Regenerate this copy")} locale={locale}/>}{d.status_code==="Generating"&&!d.canRetry&&<p className="text-sm leading-7 text-muted">{c("إذا انقطعت المحاولة، تتاح للمخوّل بالتقارير إعادة التجهيز بعد ١٥ دقيقة من بدئها.","If generation stops, an authorized member can retry after 15 minutes.")}</p>}{d.canArchive&&d.status_code==='Ready'&&<details><summary className="cursor-pointer text-sm font-medium">{c("أرشفة النسخة","Archive copy")}</summary><div className="mt-4"><DocumentForm operation="archive" fields={{document:d.id}} label={c("أرشفة","Archive")} locale={locale}><label className="flex items-center gap-3"><input name="confirm" type="checkbox" required className="size-5"/>{c("أؤكد الأرشفة مع بقاء النسخة المحفوظة","I confirm archiving while keeping the saved copy")}</label></DocumentForm></div></details>}</li>)}</ul>:<p className="panel p-6 leading-8 text-muted">{c("لا توجد مستندات محفوظة متاحة لك في هذا النطاق.","No saved documents are available in this scope.")}</p>;}
export function DocumentPager({page,more,href,label,locale="ar"}:{page:number;more:boolean;href:(page:number)=>string;label?:string;locale?:Locale}){const en=locale==="en";return <nav aria-label={label??(en?"Document pages":"صفحات المستندات")} className="mt-5 flex flex-wrap gap-5">{page>0&&<Link className="text-link" href={href(page-1)}>{en?"Previous":"السابق"}</Link>}{more&&<Link className="text-link" href={href(page+1)}>{en?"Next":"التالي"}</Link>}</nav>;}
export function DocumentsHelp({locale="ar"}:{locale?:Locale}){return <p className="leading-8 text-muted">{locale==="en"?"Each copy preserves its data and template at issue time and uses approved hours only. For a PDF, open the certificate and choose Print, then Save as PDF. University approval and external signatures are handled outside LUB.":"النسخة تحفظ بيانات وقالب وقت الإصدار وتستخدم الساعات المعتمدة فقط. لملف PDF، افتح البيان واختر طباعة من المتصفح ثم «حفظ بصيغة PDF». موافقة الجامعة والتوقيع الخارجي خارج لُبّ."}</p>;}
export function DocumentWorkspaceView({data,org,committee,page,memberPage,locale="ar"}:{data:DocumentWorkspace;org:string;committee:string|null;page:number;memberPage:number;locale?:Locale}){
 const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;
 const base=`/manage/organizations/${org}/documents`,href=(p:number,m=memberPage)=>`${base}?${new URLSearchParams({page:String(p),memberPage:String(m),...(committee?{committee}:{})})}`;
 const selected=data.scopes.some(s=>s.id===committee),scopeName=(id:string|null)=>data.scopes.find(s=>s.id===id)?.name??c('لجنة','Committee');
 const memberSelect=<label>{c("صاحب البيان","Certificate member")}<select name="member" required><option value="">{c("اختر العضوية","Choose membership")}</option>{data.members.slice(0,25).map(m=><option key={m.id} value={m.id} dir="auto">{m.name} · {c("عضوية منذ","Member since")} {m.start_date}{m.end_date&&` ${c("حتى","until")} ${m.end_date}`}</option>)}</select></label>;
 return <div className="space-y-8"><div><Link href={`/manage/organizations/${org}`} className="text-link">{c("إدارة الجهة","Manage organization")}</Link><h1 className="mt-4 text-3xl leading-normal font-bold">{c("التقارير والمستندات","Reports and documents")} · <bdi>{data.name}</bdi></h1><div className="mt-4"><DocumentsHelp locale={locale}/></div></div><form className="panel flex flex-wrap items-end gap-4 p-5"><label className="min-w-0 flex-1 basis-64">{c("النطاق","Scope")}<select name="committee" defaultValue={committee??''}>{data.scopes.map(s=><option key={s.id??'org'} value={s.id??''} dir="auto">{s.name}</option>)}</select></label><button className="button button-secondary">{c("عرض النطاق","Show scope")}</button></form>
 {!selected&&<p className="panel p-5 leading-8">{c("اختر نطاقًا مخوّلًا لإنشاء تقرير أو بيان.","Choose an authorized scope to create a report or certificate.")}</p>}{selected&&<section className="grid gap-5 lg:grid-cols-2"><div className="panel min-w-0 space-y-5 p-6"><h2 className="text-xl font-semibold">{c("تقرير ساعات CSV","CSV hours report")}</h2><DocumentForm operation="generate" fields={{org,committee:committee??'',kind:'Hours_Report'}} label={c("إنشاء التقرير","Create report")} locale={locale}><PeriodFields terms={data.terms} locale={locale}/><p className="text-sm leading-7 text-muted">{c("يجمع الساعات المعتمدة حسب العضوية دون الأرقام الجامعية أو بيانات الاتصال.","Includes approved hours by membership without university IDs or contact details.")}</p></DocumentForm></div><div className="panel min-w-0 space-y-5 p-6"><h2 className="text-xl font-semibold">{c("بيان ساعات عضو","Member hours certificate")}</h2>{data.members.length>0?<DocumentForm operation="generate" fields={{org,committee:committee??'',kind:'Hours_Certificate'}} label={c("إنشاء البيان","Create certificate")} locale={locale}>{memberSelect}<PeriodFields terms={data.terms} locale={locale}/></DocumentForm>:<p className="leading-8 text-muted">{c("لا توجد عضويات لها ساعات معتمدة في هذا النطاق.","No memberships have approved hours in this scope.")}</p>}</div></section>}
 <DocumentPager page={memberPage} more={data.members.length>25||data.grantMembers.length>25||data.grants.length>25} href={m=>href(page,m)} label={c("صفحات الأعضاء والتفويض","Member and permission pages")} locale={locale}/>
 <section className="space-y-5"><h2 className="text-xl font-semibold">{c("النسخ المحفوظة","Saved copies")}</h2><DocumentList items={data.items} locale={locale}/><DocumentPager page={page} more={data.items.length>25} href={p=>href(p)} locale={locale}/></section>
 {data.canGrant&&<section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("تفويض التقارير","Report permissions")}</h2>{data.grantMembers.length>0&&<DocumentForm operation="grant" label={c("منح صلاحية التقارير","Grant report permission")} locale={locale}><label>{c("العضو","Member")}<select name="member" required><option value="">{c("اختر العضو","Choose member")}</option>{data.grantMembers.slice(0,25).map(m=><option key={m.id} value={m.id} dir="auto">{m.name}</option>)}</select></label><label>{c("النطاق","Scope")}<select name="committee"><option value="">{c("الجهة بالكامل","Whole organization")}</option>{data.scopes.filter(s=>s.id).map(s=><option key={s.id} value={s.id!} dir="auto">{s.name}</option>)}</select></label><DateInput name="ends" label={c("انتهاء التفويض (اختياري)","Permission ends (optional)")} locale={locale}/></DocumentForm>}{data.grants.slice(0,25).map(g=><div key={g.id} className="border-t border-line pt-5"><p className="mb-3"><bdi>{g.name}</bdi> · <bdi>{scopeName(g.committee_id)}</bdi>{g.end_at&&` · ${c("ينتهي","ends")} ${new Intl.DateTimeFormat(en?'en-US':'ar-SA',{dateStyle:'medium',timeZone:'Asia/Riyadh',calendar:'gregory'}).format(new Date(g.end_at))}`}</p><DocumentForm operation="end-grant" fields={{grant:g.id}} label={c("إنهاء التفويض","End permission")} locale={locale}><label className="flex items-center gap-3"><input name="confirm" type="checkbox" required className="size-5"/>{c("أؤكد إنهاء التفويض","I confirm ending this permission")}</label></DocumentForm></div>)}</section>}</div>;
}
