"use client";
import {useState} from "react";
import {WorkflowForm} from "@/features/forms/mutation-form";
import {DateInput} from "@/features/forms/date-input";
import {mutateEvent} from "./actions";
import {ApplicationForm} from "@/features/forms/application-form";
import type {Event} from "./repository";
import type {Locale} from "@/lib/preferences";
export function EventForm(props:Omit<Parameters<typeof WorkflowForm>[0],"mutation">){return <WorkflowForm {...props} mutation={mutateEvent}/>;}
export function EventRegistrationForm(props:Parameters<typeof ApplicationForm>[0]){return <ApplicationForm {...props} mutation={mutateEvent}/>;}
export function EventFields({value,templates=[],locale="ar"}:{value?:Event;templates?:Array<{id:string;name:string}>;locale?:Locale}){const frozen=value?.status_code==="Published",en=locale==="en",c=(ar:string,english:string)=>en?english:ar;return <>
 <label>{c("عنوان الفعالية","Event title")}<input name="title" required minLength={2} maxLength={120} defaultValue={value?.title}/></label><label>{c("الوصف","Description")}<textarea name="description" maxLength={6000} rows={4} defaultValue={value?.description}/></label>
 <label>{c("طريقة الحضور","Attendance mode")}<select name="locationType" defaultValue={value?.location_type_code??"In_Person"}><option value="In_Person">{c("حضوري","In person")}</option><option value="Online">{c("عن بُعد","Online")}</option><option value="Hybrid">{c("حضوري وعن بُعد","Hybrid")}</option></select></label><label>{c("المكان","Location")}<input name="location" maxLength={500} defaultValue={value?.location_text??""}/></label><label>{c("رابط الحضور HTTPS","Attendance URL (HTTPS)")}<input name="url" type="url" dir="ltr" maxLength={2048} defaultValue={value?.online_url??""}/></label>
 <DateInput name="starts" label={c("بداية الفعالية","Event starts")} required value={value?.starts_at} locale={locale}/><DateInput name="ends" label={c("نهاية الفعالية","Event ends")} required value={value?.ends_at} locale={locale}/><DateInput name="opens" label={c("فتح التسجيل","Registration opens")} required value={value?.registration_opens_at} locale={locale}/><DateInput name="closes" label={c("إغلاق التسجيل","Registration closes")} required value={value?.registration_closes_at} locale={locale}/>
 <label>{c("السعة (فارغة بلا حد)","Capacity (blank for unlimited)")}<input name="capacity" type="number" min={1} max={10000} defaultValue={value?.capacity??""}/></label><label>{c("ساعات حضور أعضاء الجهة","Attendance hours for organization members")}<input name="hours" type="number" min={0} max={1000} step="0.01" required readOnly={frozen} defaultValue={value?.attendance_hours??"0"}/></label>
 {frozen?<input type="hidden" name="template" value={value.registration_form_template_id??""}/>:<label>{c("نموذج أسئلة إضافية","Additional questions form")}<select name="template" defaultValue={value?.registration_form_template_id??""}><option value="">{c("بدون أسئلة إضافية","No additional questions")}</option>{templates.map(t=><option key={t.id} value={t.id} dir="auto">{t.name}</option>)}</select></label>}
 <p className="text-sm leading-7 text-muted">{c("النشر بعد الموافقة الخارجية. الموعد والمكان والرابط قابلون للتعديل مع إشعار المسجلين. الساعات والنموذج يثبتان عند النشر.","Publish after external approval. Date, place and URL can be changed with a notice to registrants. Hours and the form are fixed on publication.")}</p>
 </>;}
export function EventAttachment({event,locale="ar"}:{event:string;locale?:Locale}){const [asset,setAsset]=useState("");const [pending,setPending]=useState(false);const [error,setError]=useState("");const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;async function upload(file?:File){if(!file)return;setPending(true);setError("");setAsset("");try{const body=new FormData();body.set("file",file);const response=await fetch("/files/upload",{method:"POST",body});const result=await response.json() as {id?:string};if(!response.ok||!result.id)throw new Error();setAsset(result.id);}catch{setError(c("تعذّر رفع الملف. استخدم PDF أو JPEG أو PNG حتى 5 ميجابايت.","Upload failed. Use a PDF, JPEG or PNG up to 5 MB."));}finally{setPending(false);}}return <EventForm operation="attach" fields={{event,asset}} disabled={pending||!asset} label={c("حفظ مرفق الفعالية","Save event attachment")} locale={locale}><label>{c("نوع الملف","File type")}<select name="kind"><option value="Approval">{c("الموافقة الخارجية","External approval")}</option><option value="Attendance">{c("كشف الحضور","Attendance sheet")}</option><option value="Report">{c("التقرير الختامي","Final report")}</option><option value="Photo">{c("صورة","Photo")}</option></select></label><label>{c("الملف","File")}<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={pending} onChange={e=>void upload(e.target.files?.[0])}/></label>{pending&&<p role="status">{c("جارٍ رفع الملف…","Uploading file…")}</p>}{error&&<p role="alert" className="error-message">{error}</p>}<p className="text-sm text-muted">{c("المرفقات خاصة بمشغّلي الفعالية.","Attachments are visible only to event staff.")}</p></EventForm>;}
