import "server-only";
import {sql} from "drizzle-orm";
import {unstable_cache} from "next/cache";
import {withUser,withVisitor} from "@/db/client";
import type {FormDefinition,Answers} from "@/features/forms/definition";
export type Event={id:string;organization_id:string;title:string;description:string;location_type_code:string;location_text:string|null;online_url:string|null;starts_at:string;ends_at:string;registration_opens_at:string;registration_closes_at:string;capacity:number|null;attendance_hours:string;status_code:string;is_featured:boolean;public_report:string;public_photos:string[];revision:number;registration_form_template_id:string|null};
export type EventCard=Event&{org_name:string;slug:string;open:boolean;remaining:number|null};
export const listEvents=unstable_cache(async(q:string,period:string,page:number,org:string|null=null)=>withVisitor(async tx=>{
 const rows=await tx.execute(sql`select e.id,e.title,e.starts_at,e.ends_at,e.status_code,e.location_type_code,e.location_text,e.online_url,o.name_ar as org_name,o.slug,e.organization_id,statement_timestamp()>=e.registration_opens_at and statement_timestamp()<e.registration_closes_at and e.status_code='Published' and o.status_code='Active' as open from lub.events e join lub.organizations o on o.id=e.organization_id where e.published_at is not null and (${org}::uuid is null or e.organization_id=${org}::uuid) and e.title ilike ${`%${q.replace(/[\\%_]/g,"\\$&")}%`} and (${period}='all' or (${period}='upcoming' and e.status_code='Published' and e.ends_at>=statement_timestamp()) or (${period}='past' and e.ends_at<statement_timestamp())) order by e.starts_at desc,e.id limit 25 offset ${page*24}`);return rows as unknown as EventCard[];
}),["event-discovery"],{revalidate:30,tags:["events"]});
export type EventDetail={event:Event;org_name:string;slug:string;status:string|null;onboarded:boolean;open:boolean;remaining:number|null;own:{id:string;status_code:string;attendance:string|null;response_revision:number|null;answers:Answers;version:string|null}|null;form:{id:string;definition:FormDefinition}|null;canManage:boolean;canAttend:boolean;canContribute:boolean;registrations:Array<{id:string;user_id:string;name:string;status_code:string;attendance:string;answers:Answers|null;definition:FormDefinition|null}>;contributions:Array<{id:string;title:string;name:string;contribution_type_code:string}>;assets:Array<{id:string;file_name:string;asset_type_code:string}>};
export async function myEvents(user:string,page:number){return withUser(user,async tx=>{const rows=await tx.execute(sql`select (select status_code from lub.users where id=${user}) as status,exists(select 1 from lub.student_profiles where user_id=${user}) as onboarded,coalesce((select jsonb_agg(e) from(select e.id,e.title,e.starts_at,e.status_code,r.status_code as registration,coalesce(a.status_code,'Pending') as attendance from lub.event_registrations r join lub.events e on e.id=r.event_id left join lub.event_attendance a on a.event_registration_id=r.id where r.user_id=${user} order by e.starts_at desc,e.id limit 26 offset ${page*25}) e),'[]') as events`);return rows[0] as unknown as {status:string|null;onboarded:boolean;events:Array<{id:string;title:string;starts_at:string;status_code:string;registration:string;attendance:string}>};});}
export async function eventDetail(user:string|null,id:string,page=0){if(!user)return withVisitor(async tx=>{const rows=await tx.execute(sql`select to_jsonb(e) as event,o.name_ar as org_name,o.slug,false as onboarded,null::text as status,null::jsonb as own,false as "canManage",false as "canAttend",false as "canContribute",'[]'::jsonb as registrations,'[]'::jsonb as contributions,'[]'::jsonb as assets,statement_timestamp()>=e.registration_opens_at and statement_timestamp()<e.registration_closes_at and e.status_code='Published' and o.status_code='Active' as open,lub.event_remaining(e.id) as remaining,(select jsonb_build_object('id',v.id,'definition',v.definition) from lub.form_versions v where v.form_template_id=e.registration_form_template_id and v.status_code='Published' order by v.version_number desc limit 1) as form from lub.events e join lub.organizations o on o.id=e.organization_id where e.id=${id} and e.published_at is not null`);return rows[0] as unknown as EventDetail|undefined;});return withUser(user,async tx=>{
 const rows=await tx.execute(sql`select to_jsonb(e) as event,o.name_ar as org_name,o.slug,(select status_code from lub.users where id=${user}::uuid) as status,exists(select 1 from lub.student_profiles where user_id=${user}::uuid) as onboarded,
 statement_timestamp()>=e.registration_opens_at and statement_timestamp()<e.registration_closes_at and e.status_code='Published' and o.status_code='Active' as open,
 lub.event_remaining(e.id) as remaining,
 case when ${user}::uuid is not null then (select jsonb_build_object('id',r.id,'status_code',r.status_code,'attendance',(select status_code from lub.event_attendance where event_registration_id=r.id),'response_revision',f.revision,'answers',coalesce(f.answers,'{}'),'version',f.form_version_id) from lub.event_registrations r left join lub.form_responses f on f.id=r.form_response_id where r.event_id=e.id and r.user_id=${user}::uuid) end as own,
 (select jsonb_build_object('id',v.id,'definition',v.definition) from lub.form_versions v where v.form_template_id=e.registration_form_template_id and (v.id=(select f.form_version_id from lub.event_registrations r join lub.form_responses f on f.id=r.form_response_id where r.event_id=e.id and r.user_id=${user}::uuid) or (v.status_code='Published' and not exists(select 1 from lub.event_registrations r where r.event_id=e.id and r.user_id=${user}::uuid and r.form_response_id is not null))) order by v.version_number desc limit 1) as form,
 case when ${user}::uuid is not null then lub.can_operate_event(e.id) else false end as "canManage",case when ${user}::uuid is not null then lub.can_operate_event(e.id,'EVENT_ATTENDANCE_MANAGE') else false end as "canAttend",case when ${user}::uuid is not null then lub.can_operate_event(e.id,'EVENT_CONTRIBUTIONS_MANAGE') else false end as "canContribute",
 case when ${user}::uuid is not null and lub.has_event_access(e.organization_id) then coalesce((select jsonb_agg(r) from (select rr.id,rr.user_id,lub.event_student_name(rr.id) as name,rr.status_code,coalesce(a.status_code,'Pending') as attendance,f.answers,v.definition from lub.event_registrations rr left join lub.event_attendance a on a.event_registration_id=rr.id left join lub.form_responses f on f.id=rr.form_response_id left join lub.form_versions v on v.id=f.form_version_id where rr.event_id=e.id order by rr.registered_at,rr.id limit 26 offset ${page*25}) r),'[]') else '[]'::jsonb end as registrations,
 case when ${user}::uuid is not null then coalesce((select jsonb_agg(c) from (select cc.id,cc.title,cc.contribution_type_code,lub.event_student_name(r.id) as name from lub.event_contributions cc join lub.event_registrations r on r.event_id=cc.event_id and r.user_id=cc.user_id where cc.event_id=e.id order by cc.id limit 100) c),'[]') else '[]'::jsonb end as contributions,
 case when ${user}::uuid is not null then coalesce((select jsonb_agg(a) from (select aa.id,aa.file_name,ea.asset_type_code from lub.event_assets ea join lub.application_assets aa on aa.id=ea.asset_id where ea.event_id=e.id order by aa.id limit 100) a),'[]') else '[]'::jsonb end as assets
 from lub.events e join lub.organizations o on o.id=e.organization_id where e.id=${id}`);
 return rows[0] as unknown as EventDetail|undefined;
});}
export async function eventWorkspace(user:string,org:string,page:number,memberPage=0,grantPage=0){return withUser(user,async tx=>{const rows=await tx.execute(sql`select o.name_ar as name,(select status_code from lub.users where id=${user}) as status,exists(select 1 from lub.student_profiles where user_id=${user}) as onboarded,lub.has_org_permission(o.id,'EVENTS_MANAGE') as "canManage",lub.has_org_permission(o.id,'PERMISSIONS_GRANT') as "canGrant",coalesce((select jsonb_agg(e) from(select id,title,starts_at,status_code from lub.events where organization_id=o.id order by starts_at desc,id limit 26 offset ${page*25}) e),'[]') as events,coalesce((select jsonb_agg(t) from(select id,name from lub.form_templates t where (organization_id=o.id or is_system_template) and exists(select 1 from lub.form_versions where form_template_id=t.id and status_code='Published') order by name,id limit 100) t),'[]') as templates,case when lub.has_org_permission(o.id,'PERMISSIONS_GRANT') then coalesce((select jsonb_agg(m) from lub.report_grant_members(o.id,${memberPage*25}) m),'[]') else '[]'::jsonb end as members,lub.event_grants(o.id,${grantPage*25}) as grants from lub.organizations o where o.id=${org} and (lub.has_event_access(o.id) or lub.has_org_permission(o.id,'PERMISSIONS_GRANT'))`);return rows[0] as unknown as {name:string;status:string|null;onboarded:boolean;canManage:boolean;canGrant:boolean;events:Event[];templates:Array<{id:string;name:string}>;members:Array<{id:string;name:string}>;grants:Array<{id:string;name:string;permission_code:string;end_at:string|null}>}|undefined;});}
