"use client";
import { useState } from "react";
import { fieldTypes,fieldTypesEn, type FormDefinition, type FormField } from "./definition";
import { WorkflowForm } from "./mutation-form";
import type {Locale} from "@/lib/preferences";
export function FormEditor({ version, revision, initial, locale="ar" }: { version: string; revision: number; initial: FormDefinition; locale?:Locale }) {
 const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;
 const [definition,setDefinition]=useState(initial); const [drag,setDrag]=useState<{section:number;field:number}|null>(null);
 const update=(section:number,field:number,patch:Partial<FormField>)=>setDefinition(d=>({...d,sections:d.sections.map((s,si)=>si===section?{...s,fields:s.fields.map((f,fi)=>fi===field?{...f,...patch}:f)}:s)}));
 function move(si:number,fi:number,to:number) { setDefinition(d=>({...d,sections:d.sections.map((s,index)=>{if(index!==si||to<0||to>=s.fields.length)return s;const fields=[...s.fields];const [field]=fields.splice(fi,1);fields.splice(to,0,field);return {...s,fields};})})); }
 return <WorkflowForm operation="save-form" fields={{version,revision:String(revision),definition:JSON.stringify(definition)}} label={c("حفظ المسودة","Save draft")} locale={locale}>
 <label>{c("طريقة العرض","Layout")}<select value={definition.layout} onChange={e=>setDefinition({...definition,layout:e.target.value as FormDefinition["layout"]})}><option value="SinglePage">{c("صفحة واحدة","Single page")}</option><option value="Progressive">{c("قسم في كل خطوة","One section per step")}</option></select></label>
 {definition.sections.map((section,si)=><fieldset key={section.id} className="rounded-lg border border-line p-4"><legend>{c("القسم","Section")} {si+1}</legend><div className="space-y-4">
 <label>{c("عنوان القسم","Section title")}<input dir="auto" required maxLength={120} value={section.title} onChange={e=>setDefinition({...definition,sections:definition.sections.map((s,i)=>i===si?{...s,title:e.target.value}:s)})}/></label>
 <label>{c("وصف القسم","Section description")}<textarea dir="auto" maxLength={1000} value={section.description} onChange={e=>setDefinition({...definition,sections:definition.sections.map((s,i)=>i===si?{...s,description:e.target.value}:s)})}/></label>
 {section.fields.map((field,fi)=>{
 const earlier=definition.sections.flatMap((s,i)=>i<si?s.fields:i===si?s.fields.slice(0,fi):[]).filter(f=>f.type!=="File");
 return <div key={field.id} className="space-y-3 rounded-lg bg-white p-4" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag?.section===si)move(si,drag.field,fi);setDrag(null);}}>
 <div className="flex flex-wrap gap-2"><span draggable onDragStart={()=>setDrag({section:si,field:fi})} className="cursor-grab p-2">{c("السؤال","Question")} {fi+1} ↕</span><button type="button" className="button button-secondary" disabled={!fi} onClick={()=>move(si,fi,fi-1)} aria-label={`${c("رفع السؤال","Move question up")} ${fi+1}`}>↑</button><button type="button" className="button button-secondary" disabled={fi===section.fields.length-1} onClick={()=>move(si,fi,fi+1)} aria-label={`${c("خفض السؤال","Move question down")} ${fi+1}`}>↓</button><button type="button" className="text-link" disabled={section.fields.length===1} onClick={()=>setDefinition({...definition,sections:definition.sections.map((s,i)=>i===si?{...s,fields:s.fields.filter(f=>f.id!==field.id)}:s)})}>{c("حذف السؤال","Delete question")}</button></div>
 <label>{c("السؤال","Question")}<input dir="auto" required maxLength={300} value={field.label} onChange={e=>update(si,fi,{label:e.target.value})}/></label>
 <label>{c("نوع الإجابة","Answer type")}<select value={field.type} onChange={e=>{const type=e.target.value as FormField["type"];update(si,fi,{type,options:["Select","Radio","MultiSelect"].includes(type)?[{value:"option1",label:c("الخيار الأول","First option")},{value:"option2",label:c("الخيار الثاني","Second option")}]:[]});}}>{Object.entries(fieldTypes).map(([type,label])=><option key={type} value={type}>{en?fieldTypesEn[type as keyof typeof fieldTypesEn]:label}</option>)}</select></label>
 <label>{c("توضيح اختياري","Optional help text")}<input dir="auto" maxLength={1000} value={field.help} onChange={e=>update(si,fi,{help:e.target.value})}/></label>
 <label className="flex gap-3"><input type="checkbox" className="size-5" checked={field.required} onChange={e=>update(si,fi,{required:e.target.checked})}/>{c("إجابة مطلوبة","Required answer")}</label>
 {field.options.length>0&&<><p className="text-sm text-muted">{c("الخيارات (المعرّف ثابت لحفظ الإجابات)","Options (identifiers stay fixed to preserve answers)")}</p>{field.options.map((option,oi)=><div className="flex flex-wrap gap-2" key={option.value}><input dir="auto" aria-label={`${c("الخيار","Option")} ${oi+1} ${c("للسؤال","for question")} ${fi+1}`} required maxLength={120} value={option.label} onChange={e=>update(si,fi,{options:field.options.map((o,i)=>i===oi?{...o,label:e.target.value}:o)})}/><button type="button" disabled={field.options.length<=2} onClick={()=>update(si,fi,{options:field.options.filter(o=>o.value!==option.value)})}>{c("حذف","Delete")}</button></div>)}<button type="button" className="text-link" disabled={field.options.length>=30} onClick={()=>update(si,fi,{options:[...field.options,{value:crypto.randomUUID(),label:c("خيار جديد","New option")}]})}>{c("إضافة خيار","Add option")}</button></>}
 {["ShortText","LongText"].includes(field.type)&&<label>{c("الحد الأقصى للأحرف","Maximum characters")}<input type="number" min={1} max={2000} value={field.maxLength} onChange={e=>update(si,fi,{maxLength:Number(e.target.value)})}/></label>}
 {field.type==="Number"&&<div className="grid gap-3 sm:grid-cols-2">{(["min","max"] as const).map(key=><label key={key}>{en?key==="min"?"Minimum value":"Maximum value":key==="min"?"أقل قيمة":"أعلى قيمة"}<input type="number" step="any" value={field[key]??""} onChange={e=>update(si,fi,{[key]:e.target.value===""?undefined:Number(e.target.value)})}/></label>)}</div>}
 <label>{c("شرط ظهور السؤال","Question visibility condition")}<select value={field.condition?.fieldId??""} onChange={e=>update(si,fi,{condition:e.target.value?{fieldId:e.target.value,operator:"Equals",value:"true"}:undefined})}><option value="">{c("يظهر دائمًا","Always show")}</option>{earlier.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>
 {field.condition&&<div className="grid gap-3 sm:grid-cols-2"><label>{c("المقارنة","Comparison")}<select value={field.condition.operator} onChange={e=>update(si,fi,{condition:{...field.condition!,operator:e.target.value as "Equals"|"NotEquals"}})}><option value="Equals">{c("يساوي","Equals")}</option><option value="NotEquals">{c("لا يساوي","Does not equal")}</option></select></label><label>{c("قيمة الإجابة","Answer value")}{(()=>{const previous=earlier.find(f=>f.id===field.condition?.fieldId);const opts=previous?.type==="Checkbox"?[{value:"true",label:c("موافق","Agreed")},{value:"false",label:c("غير موافق","Not agreed")}]:previous?.options??[];return opts.length?<select value={field.condition.value} onChange={e=>update(si,fi,{condition:{...field.condition!,value:e.target.value}})}><option value="">{c("اختر إجابة","Choose an answer")}</option>{opts.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input dir="auto" value={field.condition.value} maxLength={120} required onChange={e=>update(si,fi,{condition:{...field.condition!,value:e.target.value}})}/>;})()}</label></div>}
 </div>;})}
 <button type="button" className="button button-secondary" disabled={section.fields.length>=30} onClick={()=>setDefinition({...definition,sections:definition.sections.map((s,i)=>i===si?{...s,fields:[...s.fields,{id:crypto.randomUUID(),type:"ShortText",label:c("سؤال جديد","New question"),help:"",required:false,options:[],maxLength:300}]}:s)})}>{c("إضافة سؤال","Add question")}</button>
 {definition.sections.length>1&&<button type="button" className="text-link ms-4" onClick={()=>setDefinition({...definition,sections:definition.sections.filter(s=>s.id!==section.id)})}>{c("حذف القسم","Delete section")}</button>}
 </div></fieldset>)}
 <button type="button" className="button button-secondary" disabled={definition.sections.length>=12} onClick={()=>setDefinition({...definition,sections:[...definition.sections,{id:crypto.randomUUID(),title:c("قسم جديد","New section"),description:"",fields:[{id:crypto.randomUUID(),type:"ShortText",label:c("سؤال جديد","New question"),help:"",required:false,options:[],maxLength:300}]}]})}>{c("إضافة قسم","Add section")}</button>
 <p className="text-sm leading-7 text-muted">{c("احفظ المسودة، ثم انشرها. النسخ المنشورة وطلبات الطلاب السابقة تبقى ثابتة.","Save the draft, then publish it. Published versions and earlier applications remain unchanged.")}</p>
 </WorkflowForm>;
}
