GRANT SELECT ON lub.profile_organization_settings,lub.profile_links,lub.skills,lub.student_skills,lub.student_projects TO authenticated;
CREATE POLICY talent_org_owner ON lub.profile_organization_settings FOR SELECT TO authenticated USING(user_id=auth.uid() AND EXISTS(SELECT 1 FROM lub.users WHERE id=auth.uid() AND status_code='Active'));
CREATE POLICY talent_link_owner ON lub.profile_links FOR SELECT TO authenticated USING(user_id=auth.uid() AND EXISTS(SELECT 1 FROM lub.users WHERE id=auth.uid() AND status_code='Active'));
CREATE POLICY talent_skill_owner ON lub.student_skills FOR SELECT TO authenticated USING(user_id=auth.uid() AND EXISTS(SELECT 1 FROM lub.users WHERE id=auth.uid() AND status_code='Active'));
CREATE POLICY talent_skill_names ON lub.skills FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM lub.student_skills s WHERE s.skill_id=id AND s.user_id=auth.uid()));
CREATE POLICY talent_project_owner ON lub.student_projects FOR SELECT TO authenticated USING(user_id=auth.uid() AND EXISTS(SELECT 1 FROM lub.users WHERE id=auth.uid() AND status_code='Active'));
CREATE FUNCTION lub.talent_owner() RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 PERFORM 1 FROM lub.users u JOIN lub.student_profiles p ON p.user_id=u.id WHERE u.id=auth.uid() AND u.status_code='Active' FOR UPDATE OF u;
 IF NOT FOUND THEN RAISE EXCEPTION 'Active profile required' USING ERRCODE='42501';END IF;RETURN auth.uid();
END; $$;
CREATE FUNCTION lub.save_talent_settings(bio text,enabled boolean,hours boolean,roles boolean,events boolean,projects boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE owner uuid:=lub.talent_owner();
BEGIN
 UPDATE lub.student_profiles SET bio=trim(save_talent_settings.bio),updated_at=now() WHERE user_id=owner;
 INSERT INTO lub.profile_settings(user_id,public_profile_enabled,show_total_hours,show_role_history,show_events,show_projects) VALUES(owner,enabled,hours,roles,events,projects) ON CONFLICT(user_id) DO UPDATE SET public_profile_enabled=excluded.public_profile_enabled,show_total_hours=excluded.show_total_hours,show_role_history=excluded.show_role_history,show_events=excluded.show_events,show_projects=excluded.show_projects,updated_at=now();
 PERFORM lub.task_audit(owner,NULL,'TALENT_SETTINGS_UPDATED');
END; $$;
CREATE FUNCTION lub.save_talent_link(target uuid,kind text,label text,value text,visible boolean) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE owner uuid:=lub.talent_owner();result uuid;
BEGIN
 IF kind NOT IN ('Email','Phone','Website','LinkedIn','GitHub') OR value IS NULL OR (kind='Email' AND value!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$') OR (kind='Phone' AND value!~'^\+?[0-9]{8,15}$') OR (kind IN ('Website','LinkedIn','GitHub') AND value!~'^https://[^[:space:]@]+$') THEN RAISE EXCEPTION 'Invalid link'; END IF;
 IF target IS NULL THEN
  IF (SELECT count(*) FROM lub.profile_links WHERE user_id=owner)>=10 THEN RAISE EXCEPTION 'Link limit';END IF;
  INSERT INTO lub.profile_links(user_id,link_type,label,url_or_value,is_public) VALUES(owner,kind,trim(label),trim(value),visible) RETURNING id INTO result;
 ELSE UPDATE lub.profile_links SET link_type=kind,label=trim(save_talent_link.label),url_or_value=trim(value),is_public=visible WHERE id=target AND user_id=owner RETURNING id INTO result;IF NOT FOUND THEN RAISE EXCEPTION 'Owned link required';END IF;END IF;
 PERFORM lub.task_audit(result,NULL,'TALENT_LINK_SAVED');RETURN result;
END; $$;
CREATE FUNCTION lub.remove_talent_link(target uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE owner uuid:=lub.talent_owner(); BEGIN DELETE FROM lub.profile_links WHERE id=target AND user_id=owner;IF NOT FOUND THEN RAISE EXCEPTION 'Owned link required';END IF;PERFORM lub.task_audit(target,NULL,'TALENT_LINK_REMOVED');END; $$;
CREATE FUNCTION lub.save_talent_skill(name text,visible boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE owner uuid:=lub.talent_owner();skill uuid;
BEGIN
 IF length(trim(name)) NOT BETWEEN 2 AND 80 OR name IS NULL THEN RAISE EXCEPTION 'Invalid skill';END IF;
 IF (SELECT count(*) FROM lub.student_skills WHERE user_id=owner)>=30 AND NOT EXISTS(SELECT 1 FROM lub.student_skills ss JOIN lub.skills s ON s.id=ss.skill_id WHERE ss.user_id=owner AND s.name_ar=trim(name)) THEN RAISE EXCEPTION 'Skill limit';END IF;
 INSERT INTO lub.skills(name_ar) VALUES(trim(name)) ON CONFLICT(name_ar) DO UPDATE SET name_ar=excluded.name_ar RETURNING id INTO skill;
 INSERT INTO lub.student_skills(user_id,skill_id,is_public) VALUES(owner,skill,visible) ON CONFLICT(user_id,skill_id) DO UPDATE SET is_public=excluded.is_public;PERFORM lub.task_audit(skill,NULL,'TALENT_SKILL_SAVED');
END; $$;
CREATE FUNCTION lub.remove_talent_skill(name text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE owner uuid:=lub.talent_owner(); BEGIN DELETE FROM lub.student_skills WHERE user_id=owner AND skill_id IN (SELECT id FROM lub.skills WHERE name_ar=name);PERFORM lub.task_audit(owner,NULL,'TALENT_SKILL_REMOVED');END; $$;
CREATE FUNCTION lub.save_talent_project(target uuid,participant uuid,contribution uuid,title text,description text,visible boolean,featured boolean) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE owner uuid:=lub.talent_owner();result uuid;
BEGIN
 IF (participant IS NULL)=(contribution IS NULL) OR (participant IS NOT NULL AND NOT EXISTS(SELECT 1 FROM lub.task_participants WHERE id=participant AND user_id=owner AND status_code='Approved')) OR (contribution IS NOT NULL AND NOT EXISTS(SELECT 1 FROM lub.event_contributions c JOIN lub.events e ON e.id=c.event_id WHERE c.id=contribution AND c.user_id=owner AND e.status_code='Completed')) THEN RAISE EXCEPTION 'Owned verified activity required';END IF;
 IF target IS NULL THEN
 IF (SELECT count(*) FROM lub.student_projects WHERE user_id=owner)>=100 THEN RAISE EXCEPTION 'Project limit';END IF;
 INSERT INTO lub.student_projects(user_id,task_participant_id,event_contribution_id,display_title,display_description,is_public,is_featured) VALUES(owner,participant,contribution,trim(title),trim(description),visible,featured) RETURNING id INTO result;
 ELSE UPDATE lub.student_projects SET display_title=trim(title),display_description=trim(description),is_public=visible,is_featured=featured,updated_at=now() WHERE id=target AND user_id=owner AND task_participant_id IS NOT DISTINCT FROM participant AND event_contribution_id IS NOT DISTINCT FROM contribution RETURNING id INTO result;IF NOT FOUND THEN RAISE EXCEPTION 'Owned project required';END IF;END IF;
 PERFORM lub.task_audit(result,NULL,'TALENT_PROJECT_SAVED');RETURN result;
END; $$;
CREATE FUNCTION lub.set_talent_organization(org uuid,hours boolean,history boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE owner uuid:=lub.talent_owner();
BEGIN
 IF NOT EXISTS(SELECT 1 FROM lub.organization_memberships WHERE user_id=owner AND organization_id=org) THEN RAISE EXCEPTION 'Own history required';END IF;
 INSERT INTO lub.profile_organization_settings(user_id,organization_id,show_hours,show_membership_history) VALUES(owner,org,hours,history) ON CONFLICT(user_id,organization_id) DO UPDATE SET show_hours=excluded.show_hours,show_membership_history=excluded.show_membership_history;PERFORM lub.task_audit(owner,org,'TALENT_ORGANIZATION_VISIBILITY');
END; $$;
CREATE FUNCTION lub.set_talent_event(registration uuid,visible boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE owner uuid:=lub.talent_owner(); BEGIN UPDATE lub.event_registrations SET show_on_profile=visible WHERE id=registration AND user_id=owner;IF NOT FOUND THEN RAISE EXCEPTION 'Own participation required';END IF;PERFORM lub.task_audit(registration,NULL,'TALENT_EVENT_VISIBILITY');END; $$;
CREATE FUNCTION lub.set_talent_contribution(contribution uuid,visible boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE owner uuid:=lub.talent_owner(); BEGIN UPDATE lub.event_contributions SET show_on_profile=visible WHERE id=contribution AND user_id=owner;IF NOT FOUND THEN RAISE EXCEPTION 'Own contribution required';END IF;PERFORM lub.task_audit(contribution,NULL,'TALENT_CONTRIBUTION_VISIBILITY');END; $$;
CREATE FUNCTION lub.talent_directory(query text,skill text,skip int DEFAULT 0) RETURNS TABLE(id uuid,name text,major text,bio text,skills jsonb) LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT p.user_id,p.full_name_ar::text,p.major_name::text,p.bio::text,coalesce((SELECT jsonb_agg(s.name_ar ORDER BY s.name_ar) FROM lub.student_skills ss JOIN lub.skills s ON s.id=ss.skill_id WHERE ss.user_id=p.user_id AND ss.is_public AND s.is_active),'[]')
 FROM lub.student_profiles p JOIN lub.users u ON u.id=p.user_id JOIN lub.profile_settings ps ON ps.user_id=p.user_id
 WHERE u.status_code='Active' AND ps.public_profile_enabled AND (coalesce(trim(query),'')='' OR position(lower(left(trim(query),120)) in lower(p.full_name_ar))>0 OR position(lower(left(trim(query),120)) in lower(p.major_name))>0)
 AND (skill IS NULL OR EXISTS(SELECT 1 FROM lub.student_skills ss JOIN lub.skills s ON s.id=ss.skill_id WHERE ss.user_id=p.user_id AND ss.is_public AND s.is_active AND s.name_ar=skill))
 ORDER BY p.full_name_ar,p.user_id LIMIT 25 OFFSET greatest(0,least(skip,240000));
$$;
CREATE FUNCTION lub.public_talent(target uuid,org_skip int DEFAULT 0,event_skip int DEFAULT 0,project_skip int DEFAULT 0) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT jsonb_build_object('id',p.user_id,'name',p.full_name_ar,'major',p.major_name,'level',p.academic_level,'bio',p.bio,
 'total',CASE WHEN s.show_total_hours THEN coalesce((SELECT sum(h.hours)::text FROM lub.hour_records h JOIN lub.organization_memberships m ON m.id=h.organization_membership_id LEFT JOIN lub.profile_organization_settings os ON os.user_id=p.user_id AND os.organization_id=m.organization_id WHERE m.user_id=p.user_id AND h.status_code='Approved' AND coalesce(os.show_hours,true)),'0') END,
 'skills',coalesce((SELECT jsonb_agg(sk.name_ar ORDER BY sk.name_ar) FROM lub.student_skills ss JOIN lub.skills sk ON sk.id=ss.skill_id WHERE ss.user_id=p.user_id AND ss.is_public AND sk.is_active),'[]'),
 'links',coalesce((SELECT jsonb_agg(jsonb_build_object('kind',l.link_type,'label',l.label,'value',l.url_or_value) ORDER BY l.id) FROM lub.profile_links l WHERE l.user_id=p.user_id AND l.is_public),'[]'),
 'organizations',coalesce((SELECT jsonb_agg(x) FROM(SELECT o.id,o.name_ar AS name,o.slug,o.status_code='Archived' AS archived,
 CASE WHEN s.show_total_hours AND coalesce(os.show_hours,true) THEN coalesce((SELECT sum(h.hours)::text FROM lub.hour_records h JOIN lub.organization_memberships mm ON mm.id=h.organization_membership_id WHERE mm.user_id=p.user_id AND mm.organization_id=o.id AND h.status_code='Approved'),'0') END AS hours,
 CASE WHEN s.show_role_history AND coalesce(os.show_membership_history,true) THEN coalesce((SELECT jsonb_agg(membership) FROM(SELECT m.start_date,m.end_date,m.status_code,coalesce((SELECT jsonb_agg(jsonb_build_object('code',r.role_code,'starts',r.start_date,'ends',r.end_date) ORDER BY r.start_date,r.id) FROM lub.role_assignments r WHERE r.organization_membership_id=m.id),'[]') AS roles FROM lub.organization_memberships m WHERE m.user_id=p.user_id AND m.organization_id=o.id ORDER BY m.start_date,m.id LIMIT 100) membership),'[]') ELSE '[]'::jsonb END AS memberships
 FROM lub.organizations o LEFT JOIN lub.profile_organization_settings os ON os.organization_id=o.id AND os.user_id=p.user_id WHERE EXISTS(SELECT 1 FROM lub.organization_memberships m WHERE m.organization_id=o.id AND m.user_id=p.user_id) AND ((s.show_role_history AND coalesce(os.show_membership_history,true)) OR (s.show_total_hours AND coalesce(os.show_hours,true))) ORDER BY o.name_ar,o.id LIMIT 26 OFFSET greatest(0,least(org_skip,250000))) x),'[]'),
 'events',CASE WHEN s.show_events THEN coalesce((SELECT jsonb_agg(x) FROM(SELECT e.id,e.title,e.starts_at,o.name_ar AS organization,o.status_code='Archived' AS archived,coalesce((SELECT jsonb_agg(jsonb_build_object('kind',c.contribution_type_code,'title',c.title) ORDER BY c.id) FROM lub.event_contributions c WHERE c.event_id=e.id AND c.user_id=p.user_id AND c.show_on_profile),'[]') AS contributions FROM lub.event_registrations r LEFT JOIN lub.event_attendance a ON a.event_registration_id=r.id JOIN lub.events e ON e.id=r.event_id JOIN lub.organizations o ON o.id=e.organization_id WHERE r.user_id=p.user_id AND r.show_on_profile AND r.status_code='Registered' AND (a.status_code='Present' OR EXISTS(SELECT 1 FROM lub.event_contributions ec WHERE ec.event_id=e.id AND ec.user_id=p.user_id AND ec.show_on_profile)) AND e.status_code='Completed' AND e.published_at IS NOT NULL ORDER BY e.starts_at DESC,e.id LIMIT 26 OFFSET greatest(0,least(event_skip,250000))) x),'[]') ELSE '[]'::jsonb END,
 'projects',CASE WHEN s.show_projects THEN coalesce((SELECT jsonb_agg(x) FROM(SELECT sp.id,sp.display_title AS title,sp.display_description AS description,sp.is_featured AS featured FROM lub.student_projects sp WHERE sp.user_id=p.user_id AND sp.is_public AND ((sp.task_participant_id IS NOT NULL AND EXISTS(SELECT 1 FROM lub.task_participants tp WHERE tp.id=sp.task_participant_id AND tp.user_id=p.user_id AND tp.status_code='Approved')) OR (sp.event_contribution_id IS NOT NULL AND EXISTS(SELECT 1 FROM lub.event_contributions c JOIN lub.events e ON e.id=c.event_id WHERE c.id=sp.event_contribution_id AND c.user_id=p.user_id AND e.status_code='Completed'))) ORDER BY sp.is_featured DESC,sp.created_at DESC,sp.id LIMIT 26 OFFSET greatest(0,least(project_skip,250000))) x),'[]') ELSE '[]'::jsonb END)
 FROM lub.student_profiles p JOIN lub.profile_settings s ON s.user_id=p.user_id JOIN lub.users u ON u.id=p.user_id WHERE p.user_id=target AND u.status_code='Active' AND s.public_profile_enabled;
$$;
CREATE FUNCTION lub.talent_workspace(org_skip int DEFAULT 0,event_skip int DEFAULT 0,project_skip int DEFAULT 0,source_skip int DEFAULT 0) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT CASE WHEN u.status_code='Inactive' THEN jsonb_build_object('status','Inactive','onboarded',false) ELSE jsonb_build_object('status',u.status_code,'onboarded',p.user_id IS NOT NULL,'bio',coalesce(p.bio,''),'settings',coalesce(to_jsonb(s)-'user_id'-'updated_at','{}'),
 'links',coalesce((SELECT jsonb_agg(l ORDER BY l.id) FROM lub.profile_links l WHERE l.user_id=u.id),'[]'),
 'skills',coalesce((SELECT jsonb_agg(jsonb_build_object('name',sk.name_ar,'public',ss.is_public) ORDER BY sk.name_ar) FROM lub.student_skills ss JOIN lub.skills sk ON sk.id=ss.skill_id WHERE ss.user_id=u.id),'[]'),
 'projects',coalesce((SELECT jsonb_agg(x) FROM(SELECT sp.id,sp.task_participant_id,sp.event_contribution_id,sp.display_title,sp.display_description,sp.is_public,sp.is_featured FROM lub.student_projects sp WHERE sp.user_id=u.id ORDER BY sp.created_at DESC,sp.id LIMIT 26 OFFSET greatest(0,least(project_skip,250000))) x),'[]'),
 'sources',coalesce((SELECT jsonb_agg(x) FROM(SELECT tp.id,'Task' AS kind,(SELECT r.snapshot_json->>'title' FROM lub.task_revisions r WHERE r.task_id=tp.task_id ORDER BY r.revision_number DESC LIMIT 1) AS title FROM lub.task_participants tp WHERE tp.user_id=u.id AND tp.status_code='Approved' AND NOT EXISTS(SELECT 1 FROM lub.student_projects sp WHERE sp.task_participant_id=tp.id) UNION ALL SELECT c.id,'Event',c.title FROM lub.event_contributions c JOIN lub.events e ON e.id=c.event_id WHERE c.user_id=u.id AND e.status_code='Completed' AND NOT EXISTS(SELECT 1 FROM lub.student_projects sp WHERE sp.event_contribution_id=c.id) ORDER BY id LIMIT 26 OFFSET greatest(0,least(source_skip,250000))) x),'[]'),
 'organizations',coalesce((SELECT jsonb_agg(x) FROM(SELECT o.id,o.name_ar AS name,coalesce(os.show_hours,true) AS hours,coalesce(os.show_membership_history,true) AS history FROM lub.organizations o LEFT JOIN lub.profile_organization_settings os ON os.user_id=u.id AND os.organization_id=o.id WHERE EXISTS(SELECT 1 FROM lub.organization_memberships m WHERE m.user_id=u.id AND m.organization_id=o.id) ORDER BY o.name_ar,o.id LIMIT 26 OFFSET greatest(0,least(org_skip,250000))) x),'[]'),
 'events',coalesce((SELECT jsonb_agg(x) FROM(SELECT r.id,e.title,r.show_on_profile AS visible,coalesce((SELECT jsonb_agg(jsonb_build_object('id',c.id,'title',c.title,'visible',c.show_on_profile)) FROM lub.event_contributions c WHERE c.event_id=e.id AND c.user_id=u.id),'[]') AS contributions FROM lub.event_registrations r LEFT JOIN lub.event_attendance a ON a.event_registration_id=r.id JOIN lub.events e ON e.id=r.event_id WHERE r.user_id=u.id AND r.status_code='Registered' AND (a.status_code='Present' OR EXISTS(SELECT 1 FROM lub.event_contributions ec WHERE ec.event_id=e.id AND ec.user_id=u.id)) AND e.status_code='Completed' ORDER BY e.starts_at DESC,e.id LIMIT 26 OFFSET greatest(0,least(event_skip,250000))) x),'[]'))
 END FROM lub.users u LEFT JOIN lub.student_profiles p ON p.user_id=u.id LEFT JOIN lub.profile_settings s ON s.user_id=u.id WHERE u.id=auth.uid();
$$;
REVOKE ALL ON FUNCTION lub.talent_owner(),lub.save_talent_settings(text,boolean,boolean,boolean,boolean,boolean),lub.save_talent_link(uuid,text,text,text,boolean),lub.remove_talent_link(uuid),lub.save_talent_skill(text,boolean),lub.remove_talent_skill(text),lub.save_talent_project(uuid,uuid,uuid,text,text,boolean,boolean),lub.set_talent_organization(uuid,boolean,boolean),lub.set_talent_event(uuid,boolean),lub.set_talent_contribution(uuid,boolean),lub.talent_directory(text,text,int),lub.public_talent(uuid,int,int,int),lub.talent_workspace(int,int,int,int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION lub.save_talent_settings(text,boolean,boolean,boolean,boolean,boolean),lub.save_talent_link(uuid,text,text,text,boolean),lub.remove_talent_link(uuid),lub.save_talent_skill(text,boolean),lub.remove_talent_skill(text),lub.save_talent_project(uuid,uuid,uuid,text,text,boolean,boolean),lub.set_talent_organization(uuid,boolean,boolean),lub.set_talent_event(uuid,boolean),lub.set_talent_contribution(uuid,boolean),lub.talent_workspace(int,int,int,int) TO authenticated;
GRANT EXECUTE ON FUNCTION lub.talent_directory(text,text,int),lub.public_talent(uuid,int,int,int) TO anon,authenticated;
