import { PGlite } from "@electric-sql/pglite";
import { readdirSync, readFileSync } from "node:fs";
import { afterAll, afterEach, beforeAll, beforeEach, expect, it } from "vitest";
import { storageFixture } from "./storage-fixture";
import {initialDefinition} from "@/features/forms/definition";
let db:PGlite;
const leader="00000000-0000-4000-8000-000000000001", student="00000000-0000-4000-8000-000000000002", peer="00000000-0000-4000-8000-000000000003", org="00000000-0000-4000-8000-000000000101";
async function actor(id:string){await db.exec("reset role");await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('role','authenticated',true)",[id]);}
async function denied(fn:()=>Promise<unknown>){await db.exec("savepoint denied");await expect(fn()).rejects.toThrow();await db.exec("rollback to savepoint denied;release savepoint denied");}
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await storageFixture(db);for(const f of readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())await db.exec(readFileSync(`drizzle/${f}`,"utf8"));},30000);
beforeEach(async()=>{await db.exec("begin");for(const [i,id] of [leader,student,peer].entries()){await db.query("insert into auth.users values($1)",[id]);await db.query("insert into lub.users(id,email,email_verified_at) values($1,$2,now())",[id,`event${i}@example.invalid`]);await db.query("insert into lub.student_profiles(user_id,full_name_ar,university_id_ciphertext,university_id_lookup_hash,major_name,academic_level) values($1,$2,'private',$3,'الحاسب','4')",[id,`طالب ${i}`,String(i).repeat(64)]);}await db.query("insert into lub.organizations(id,type_code,slug,name_ar) values($1,'Club','events-test','نادي الاختبار')",[org]);const m=(await db.query<{id:string}>("insert into lub.organization_memberships(organization_id,user_id) values($1,$2) returning id",[org,leader])).rows[0].id;await db.query("insert into lub.role_assignments(organization_membership_id,organization_id,role_code,is_primary_leader,assigned_by_user_id) values($1,$2,'OL',true,$3)",[m,org,leader]);await actor(leader);});
afterEach(async()=>{await db.exec("rollback");});afterAll(async()=>{await db.close();});
async function create(capacity=1){return(await db.query<{id:string}>("select lub.save_event(null,$1,'ورشة الاختبار','وصف الفعالية','In_Person','القاعة',null,now()+interval '1 day',now()+interval '2 days',now()-interval '1 hour',now()+interval '12 hours',$2,null,2,null) as id",[org,capacity])).rows[0].id;}
async function publish(event:string){await db.query("select lub.change_event_status($1,'Published',1)",[event]);}
async function register(event:string){return(await db.query<{id:string}>("select lub.register_event($1,null,'{}',null) as id",[event])).rows[0].id;}

it("links tasks to scoped events with immutable revisions and rejects stale or unrelated changes",async()=>{
 const event=await create();const task=(await db.query<{id:string}>("select lub.save_task(null,$1,null,null,'مهمة مرتبطة','وصف داخلي',null,null,0,null) as id",[org])).rows[0].id;
 await db.query("select lub.link_task_event($1,$2,1)",[task,event]);
 expect((await db.query<{snapshot_json:{event_id:string}}>("select snapshot_json from lub.task_revisions where task_id=$1 order by revision_number desc limit 1",[task])).rows[0].snapshot_json.event_id).toBe(event);
 await denied(()=>db.query("select lub.link_task_event($1,null,1)",[task]));
 await actor(peer);await denied(()=>db.query("select lub.link_task_event($1,null,2)",[task]));
 await db.exec("reset role");const otherOrg=(await db.query<{id:string}>("insert into lub.organizations(type_code,slug,name_ar) values('Club','other-event','جهة أخرى') returning id")).rows[0].id;
 const unrelated=(await db.query<{id:string}>("insert into lub.events(organization_id,created_by_user_id,title,description,location_type_code,location_text,starts_at,ends_at,registration_opens_at,registration_closes_at) values($1,$2,'فعالية أخرى','وصف','In_Person','قاعة',now()+interval '1 day',now()+interval '2 days',now(),now()+interval '12 hours') returning id",[otherOrg,leader])).rows[0].id;
 await actor(leader);await denied(()=>db.query("select lub.link_task_event($1,$2,2)",[task,unrelated]));
 await db.query("select lub.link_task_event($1,null,2)",[task]);
 expect((await db.query<{snapshot_json:{event_id:string|null}}>("select snapshot_json from lub.task_revisions where task_id=$1 order by revision_number desc limit 1",[task])).rows[0].snapshot_json.event_id).toBeNull();
 await db.query("select lub.change_task_status($1,'Cancelled',3)",[task]);await denied(()=>db.query("select lub.link_task_event($1,$2,4)",[task,event]));
});

it("lets delegated task managers link public events but keeps private drafts outside their capability",async()=>{
 const event=await create();const task=(await db.query<{id:string}>("select lub.save_task(null,$1,null,null,'مهمة مستقلة','وصف',null,null,0,null) as id",[org])).rows[0].id;
 await db.exec('reset role');const member=(await db.query<{id:string}>("insert into lub.organization_memberships(organization_id,user_id) values($1,$2) returning id",[org,student])).rows[0].id;
 await actor(leader);await db.query("select lub.grant_task_permission($1,'TASKS_MANAGE',null,null)",[member]);await actor(student);await denied(()=>db.query("select lub.link_task_event($1,$2,1)",[task,event]));
 await actor(leader);await publish(event);await actor(student);await db.query("select lub.link_task_event($1,$2,1)",[task,event]);expect((await db.query<{event_id:string}>("select event_id from lub.tasks where id=$1",[task])).rows[0].event_id).toBe(event);
});
it("publishes for visitors while keeping drafts and registration identities private",async()=>{const e=await create();await db.exec("reset role;set local role anon");expect((await db.query("select id from lub.events")).rows).toHaveLength(0);await denied(()=>register(e));await actor(leader);await publish(e);await db.exec("reset role;set local role anon");expect((await db.query("select id from lub.events")).rows).toEqual([{id:e}]);await denied(()=>db.query("select * from lub.event_registrations"));});
it("serializes capacity, registers once, supports cancellation and respects closing time",async()=>{const e=await create();await publish(e);await actor(student);const r=await register(e);expect(await register(e)).toBe(r);await actor(peer);await denied(()=>register(e));await actor(student);await db.query("select lub.cancel_event_registration($1)",[r]);await actor(peer);await register(e);await actor(student);await denied(()=>register(e));await db.exec("reset role");await db.query("update lub.events set registration_closes_at=now()-interval '1 minute' where id=$1",[e]);await actor(peer);await denied(()=>register(e));});
it("denies SA-only event operations, direct writes, stale edits and peer registration reads",async()=>{const e=await create();await publish(e);await actor(student);await register(e);await actor(peer);expect((await db.query("select id from lub.event_registrations")).rows).toHaveLength(0);await denied(()=>db.query("update lub.events set title='اختراق'"));await db.exec("reset role");await db.query("insert into lub.global_role_assignments(user_id,role_code,assigned_by_user_id) values($1,'SA',$1)",[peer]);await actor(peer);await denied(()=>create());await actor(leader);await denied(()=>db.query("select lub.change_event_status($1,'Cancelled',1)",[e]));});
it("notifies registered users on published edits and cancellation without deleting history",async()=>{const e=await create();await publish(e);await actor(student);await register(e);await actor(leader);await db.query("select lub.save_event($1,$2,'موعد جديد','وصف','Online',null,'https://example.invalid',now()+interval '3 days',now()+interval '4 days',now()-interval '1 hour',now()+interval '12 hours',1,null,2,2)",[e,org]);await db.query("select lub.change_event_status($1,'Cancelled',3)",[e]);await actor(student);expect((await db.query("select id from lub.notifications where target_url=$1",[`/events/${e}`])).rows.length).toBeGreaterThanOrEqual(3);expect((await db.query("select id from lub.event_registrations")).rows).toHaveLength(1);});
it("awards only eligible original members on manual completion, once, and rolls back missing term",async()=>{const e=await create();await publish(e);await actor(student);const r=await register(e);await actor(leader);await db.query("select lub.mark_event_attendance($1,'Present')",[r]);expect((await db.query("select id from lub.hour_records")).rows).toHaveLength(0);await db.exec("reset role");await db.query("update lub.events set starts_at=now()-interval '2 days',ends_at=now()-interval '1 day',registration_opens_at=now()-interval '4 days',registration_closes_at=now()-interval '3 days' where id=$1",[e]);await db.query("insert into lub.organization_memberships(organization_id,user_id,start_date) values($1,$2,current_date-10)",[org,student]);await actor(leader);await denied(()=>db.query("select lub.change_event_status($1,'Completed',2)",[e]));await db.exec("reset role");await db.exec("insert into lub.academic_terms(academic_year,term_code,name_ar,start_date,end_date) values('test','T1','الفصل',current_date-30,current_date+30)");await actor(leader);await db.query("select lub.change_event_status($1,'Completed',2)",[e]);expect((await db.query("select hours,status_code,source_code from lub.hour_records")).rows).toEqual([{hours:"2.00",status_code:"Approved",source_code:"EVENT"}]);await denied(()=>db.query("select lub.change_event_status($1,'Completed',3)",[e]));await denied(()=>db.query("select lub.mark_event_attendance($1,'Absent')",[r]));});
it("keeps outside attendees eligible to register, but never fabricates memberships or hours",async()=>{const e=await create();await publish(e);await actor(student);const r=await register(e);await actor(leader);await db.query("select lub.mark_event_attendance($1,'Present')",[r]);await db.query("select lub.verify_event_contribution($1,$2,'Trainer','تقديم الورشة')",[e,student]);await db.exec("reset role");await db.query("update lub.events set starts_at=now()-interval '2 days',ends_at=now()-interval '1 day',registration_opens_at=now()-interval '4 days',registration_closes_at=now()-interval '3 days' where id=$1",[e]);await actor(leader);await db.query("select lub.change_event_status($1,'Completed',2)",[e]);expect((await db.query("select id from lub.hour_records")).rows).toHaveLength(0);expect((await db.query("select id from lub.event_contributions")).rows).toHaveLength(1);});
it("pins form versions, validates required answers and rejects stale response edits",async()=>{
 const e=await create(5);const template=(await db.query<{id:string}>("select lub.create_form($1,'نموذج الفعالية',null) as id",[org])).rows[0].id;const v=(await db.query<{id:string}>("select id from lub.form_versions where form_template_id=$1",[template])).rows[0].id;
 await db.query("select lub.save_form_draft($1,$2::jsonb,1)",[v,JSON.stringify(initialDefinition)]);await db.query("select lub.publish_form_version($1)",[v]);await db.exec("reset role");await db.query("update lub.events set registration_form_template_id=$1 where id=$2",[template,e]);await actor(leader);await publish(e);await actor(student);await denied(()=>register(e));const answers={[initialDefinition.sections[0].fields[0].id]:"أرغب بالمشاركة"};
 const r=(await db.query<{id:string}>("select lub.register_event($1,$2,$3::jsonb,null) as id",[e,v,JSON.stringify(answers)])).rows[0].id;await denied(()=>db.query("select lub.register_event($1,$2,$3::jsonb,8)",[e,v,JSON.stringify(answers)]));await db.query("select lub.register_event($1,$2,$3::jsonb,1)",[e,v,JSON.stringify(answers)]);expect((await db.query("select revision,form_version_id from lub.form_responses")).rows).toEqual([{revision:2,form_version_id:v}]);
 await actor(peer);expect((await db.query("select id from lub.form_responses")).rows).toEqual([]);await denied(()=>db.query("select lub.cancel_event_registration($1)",[r]));await actor(leader);expect((await db.query("select answers from lub.form_responses")).rows).toHaveLength(1);
});
it("delegates only organization capabilities and revokes event access immediately",async()=>{await db.exec("reset role");const m=(await db.query<{id:string}>("insert into lub.organization_memberships(organization_id,user_id) values($1,$2) returning id",[org,student])).rows[0].id;await actor(leader);await db.query("select lub.grant_event_permission($1,'EVENT_ATTENDANCE_MANAGE',null)",[m]);const e=await create();await publish(e);await actor(peer);const r=await register(e);await actor(student);await db.query("select lub.mark_event_attendance($1,'Present')",[r]);await denied(()=>create());await actor(leader);const g=(await db.query<{id:string}>("select id from lub.permission_grants where permission_code='EVENT_ATTENDANCE_MANAGE'")).rows[0].id;await db.query("select lub.end_event_permission($1)",[g]);await actor(student);await denied(()=>db.query("select lub.mark_event_attendance($1,'Absent')",[r]));});
