import {PGlite} from "@electric-sql/pglite";
import {readFileSync,readdirSync} from "node:fs";
import {afterAll,afterEach,beforeAll,beforeEach,expect,it} from "vitest";
import {storageFixture} from "./storage-fixture";
let db:PGlite;const owner="00000000-0000-4000-8000-000000000001",peer="00000000-0000-4000-8000-000000000002",org="00000000-0000-4000-8000-000000000101";
async function actor(user:string){await db.exec("reset role");await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('role','authenticated',true)",[user]);}
async function visitor(){await db.exec("reset role");await db.exec("select set_config('request.jwt.claim.sub','',true);set local role anon");}
async function denied(fn:()=>Promise<unknown>){await db.exec("savepoint denied");await expect(fn()).rejects.toThrow();await db.exec("rollback to savepoint denied;release savepoint denied");}
async function profile(){return(await db.query<{profile:Record<string,unknown>|null}>("select lub.public_talent($1,0,0,0) as profile",[owner])).rows[0].profile;}
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role lub_runtime;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await storageFixture(db);for(const f of readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())await db.exec(readFileSync(`drizzle/${f}`,"utf8"));},30000);
beforeEach(async()=>{await db.exec("begin");for(const [i,user] of [owner,peer].entries()){await db.query("insert into auth.users values($1)",[user]);await db.query("insert into lub.users(id,email,phone,email_verified_at) values($1,$2,$3,now())",[user,`private${i}@example.invalid`,`050000000${i}`]);await db.query("insert into lub.student_profiles(user_id,full_name_ar,university_id_ciphertext,university_id_lookup_hash,major_name,academic_level) values($1,$2,'sensitive-cipher',$3,'الحاسب','4')",[user,`طالب ${i}`,String(i).repeat(64)]);await db.query("insert into lub.profile_settings(user_id) values($1)",[user]);}await actor(owner);});
afterEach(async()=>{await db.exec("rollback");});afterAll(async()=>{await db.close();});
async function publish(){await db.query("select lub.save_talent_settings('نبذة الطالب',true,true,true,true,true)");}
it("starts private, publishes only safe DTO fields and revokes visibility immediately",async()=>{await visitor();expect(await profile()).toBeNull();await actor(owner);await publish();await visitor();expect((await profile())?.name).toBe("طالب 0");const serialized=JSON.stringify(await profile());expect(serialized).not.toMatch(/sensitive-cipher|private0|0500000000|lookup_hash|university_id/);await denied(()=>db.query("select university_id_ciphertext from lub.student_profiles"));await actor(owner);await db.query("select lub.save_talent_settings('',false,true,true,true,true)");await visitor();expect(await profile()).toBeNull();expect((await db.query("select * from lub.talent_directory('',null,0)")).rows).toEqual([]);});
it("publishes contacts independently and rejects unsafe links and peer edits",async()=>{await publish();const link=(await db.query<{id:string}>("select lub.save_talent_link(null,'Email','البريد','contact@example.invalid',false) as id")).rows[0].id;await db.query("select lub.save_talent_link(null,'Website','الموقع','https://example.invalid',true)");await visitor();expect((await profile())?.links).toEqual([expect.objectContaining({kind:"Website"})]);await actor(peer);await denied(()=>db.query("select lub.save_talent_link($1,'Email','اختراق','peer@example.invalid',true)",[link]));await actor(owner);await denied(()=>db.query("select lub.save_talent_link(null,'Website','اختراق','javascript:alert(1)',true)"));await db.query("select lub.save_talent_link($1,'Email','البريد','contact@example.invalid',true)",[link]);await visitor();expect((await profile())?.links).toHaveLength(2);});
it("searches only public self-declared skills and never discovers disabled profiles",async()=>{await publish();await db.query("select lub.save_talent_skill('تصميم',true)");await db.query("select lub.save_talent_skill('مهارة مخفية',false)");await visitor();expect((await profile())?.skills).toEqual(["تصميم"]);expect((await db.query("select * from lub.talent_directory('طالب','تصميم',0)")).rows).toHaveLength(1);expect((await db.query("select * from lub.talent_directory('','مهارة مخفية',0)")).rows).toEqual([]);await actor(owner);await db.query("select lub.remove_talent_skill('تصميم')");await visitor();expect((await profile())?.skills).toEqual([]);});
it("lets the least-privilege Worker call only the public talent projections without an anon transaction",async()=>{await publish();await db.exec("reset role;set local role lub_runtime");expect((await db.query("select * from lub.talent_directory('',null,0)")).rows).toHaveLength(1);const rows=await db.query<{profile:Record<string,unknown>|null}>("select lub.public_talent($1,0,0,0) as profile",[owner]);expect(rows.rows[0].profile).toMatchObject({name:"طالب 0"});await denied(()=>db.query("select university_id_ciphertext from lub.student_profiles"));await denied(()=>db.query("select lub.save_talent_settings('',false,true,true,true,true)"));});
it("allows only owned verified activity projects and keeps original task content private",async()=>{await db.exec("reset role");await db.query("insert into lub.organizations(id,type_code,slug,name_ar) values($1,'Club','talent-test','نادي الاختبار')",[org]);const m=(await db.query<{id:string}>("insert into lub.organization_memberships(organization_id,user_id) values($1,$2) returning id",[org,owner])).rows[0].id;await db.query("insert into lub.role_assignments(organization_membership_id,organization_id,role_code,is_primary_leader,assigned_by_user_id) values($1,$2,'OL',true,$3)",[m,org,owner]);await actor(owner);await publish();await denied(()=>db.query("select lub.save_talent_project(null,null,null,'إنجاز خارجي','غير موثق',true,false)"));const task=(await db.query<{id:string}>("select lub.save_task(null,$1,null,null,'عنوان داخلي','وصف داخلي سري',null,null,0,null) as id",[org])).rows[0].id;await db.query("select lub.change_task_status($1,'Open',1)",[task]);const p=(await db.query<{id:string}>("select lub.join_task($1) as id",[task])).rows[0].id;await denied(()=>db.query("select lub.save_talent_project(null,$1,null,'عنوان عام','ملخص اختاره الطالب',true,true)",[p]));await db.exec("reset role");await db.exec("insert into lub.academic_terms(academic_year,term_code,name_ar,start_date,end_date) values('test','T1','الفصل',current_date-5,current_date+5)");await actor(owner);const submission=(await db.query<{id:string}>("select lub.submit_task($1,'مخرج خاص','{}'::uuid[],0,2) as id",[p])).rows[0].id;await db.query("select lub.review_task_submission($1,'Approved','',null)",[submission]);const project=(await db.query<{id:string}>("select lub.save_talent_project(null,$1,null,'عنوان عام','ملخص اختاره الطالب',true,true) as id",[p])).rows[0].id;await actor(peer);await denied(()=>db.query("select lub.save_talent_project($1,$2,null,'اختراق','',true,false)",[project,p]));await visitor();const publicData=JSON.stringify(await profile());expect(publicData).toContain("عنوان عام");expect(publicData).not.toMatch(/عنوان داخلي|وصف داخلي سري|task_participant_id|asset_id/);});
it("hides organization hours from both distribution and displayed total, preserving archived history",async()=>{await db.exec("reset role");await db.query("insert into lub.organizations(id,type_code,slug,name_ar) values($1,'Club','hours-talent','نادي الساعات')",[org]);const m=(await db.query<{id:string}>("insert into lub.organization_memberships(organization_id,user_id) values($1,$2) returning id",[org,owner])).rows[0].id;await db.query("insert into lub.role_assignments(organization_membership_id,organization_id,role_code,is_primary_leader,assigned_by_user_id) values($1,$2,'OL',true,$3)",[m,org,owner]);const term=(await db.query<{id:string}>("insert into lub.academic_terms(academic_year,term_code,name_ar,start_date,end_date) values('test','T1','الفصل',current_date-5,current_date+5) returning id")).rows[0].id;await actor(owner);await db.query("select lub.add_hours($1,null,$2,4,current_date,'عمل خاص',false)",[m,term]);await publish();await visitor();expect((await profile())?.total).toBe("4.00");await actor(owner);await db.query("select lub.set_talent_organization($1,false,false)",[org]);await visitor();expect((await profile())?.total).toBe("0");expect((await profile())?.organizations).toEqual([]);await actor(owner);await db.query("select lub.set_talent_organization($1,true,true)",[org]);await db.exec("reset role");await db.query("insert into lub.global_role_assignments(user_id,role_code,assigned_by_user_id) values($1,'SA',$1)",[owner]);await actor(owner);await db.query("select lub.set_organization_status($1,'Archived')",[org]);await visitor();expect((await profile())?.organizations).toEqual([expect.objectContaining({archived:true})]);});
it("allows independent event/contribution privacy and denies inactive owners",async()=>{
 await db.exec("reset role");await db.query("insert into lub.organizations(id,type_code,slug,name_ar) values($1,'Club','event-talent','نادي الفعاليات')",[org]);const e=(await db.query<{id:string}>("insert into lub.events(organization_id,created_by_user_id,title,description,location_type_code,location_text,starts_at,ends_at,registration_opens_at,registration_closes_at,status_code,published_at,completed_at) values($1,$2,'فعالية مكتملة','وصف','In_Person','القاعة',now()-interval '2 days',now()-interval '1 day',now()-interval '4 days',now()-interval '3 days','Completed',now()-interval '4 days',now()) returning id",[org,owner])).rows[0].id;const r=(await db.query<{id:string}>("insert into lub.event_registrations(event_id,user_id) values($1,$2) returning id",[e,owner])).rows[0].id;await db.query("insert into lub.event_attendance(event_registration_id,status_code,checked_in_at,marked_by_user_id) values($1,'Present',now(),$2)",[r,owner]);const c=(await db.query<{id:string}>("insert into lub.event_contributions(event_id,user_id,contribution_type_code,title,verified_by_user_id) values($1,$2,'Trainer','تقديم الورشة',$2) returning id",[e,owner])).rows[0].id;
 await actor(owner);await publish();await visitor();expect((await profile())?.events).toEqual([expect.objectContaining({id:e,contributions:[{kind:"Trainer",title:"تقديم الورشة"}]})]);await actor(owner);await db.query("select lub.set_talent_contribution($1,false)",[c]);await visitor();expect((await profile())?.events).toEqual([expect.objectContaining({contributions:[]})]);await actor(owner);await db.query("select lub.set_talent_event($1,false)",[r]);await visitor();expect((await profile())?.events).toEqual([]);await actor(peer);await denied(()=>db.query("select lub.set_talent_event($1,true)",[r]));await db.exec("reset role");await db.query("update lub.users set status_code='Inactive' where id=$1",[owner]);await actor(owner);await denied(()=>publish());await visitor();expect(await profile()).toBeNull();
});

it("retains hidden verified contributions in the owner's privacy workspace without attendance",async()=>{
 await db.exec("reset role");
 await db.query("insert into lub.organizations(id,type_code,slug,name_ar) values($1,'Club','contribution-privacy','نادي الاختبار')",[org]);
 const event=(await db.query<{id:string}>("insert into lub.events(organization_id,created_by_user_id,title,description,location_type_code,location_text,starts_at,ends_at,registration_opens_at,registration_closes_at,status_code,published_at,completed_at) values($1,$2,'ورشة','وصف','In_Person','قاعة',now()-interval '2 days',now()-interval '1 day',now()-interval '4 days',now()-interval '3 days','Completed',now()-interval '4 days',now()) returning id",[org,owner])).rows[0].id;
 const registration=(await db.query<{id:string}>("insert into lub.event_registrations(event_id,user_id) values($1,$2) returning id",[event,owner])).rows[0].id;
 await db.query("insert into lub.event_attendance(event_registration_id,status_code,marked_by_user_id) values($1,'Excused',$2)",[registration,owner]);
 const contribution=(await db.query<{id:string}>("insert into lub.event_contributions(event_id,user_id,contribution_type_code,title,verified_by_user_id) values($1,$2,'Trainer','مساهمة مثبتة',$2) returning id",[event,owner])).rows[0].id;
 await actor(owner);await publish();await visitor();expect((await profile())?.events).toHaveLength(1);
 await actor(owner);await db.query("select lub.set_talent_contribution($1,false)",[contribution]);
 const workspace=(await db.query<{data:{events:unknown[]}}>("select lub.talent_workspace() as data")).rows[0].data;
 expect(workspace.events).toEqual([expect.objectContaining({id:registration,contributions:[expect.objectContaining({id:contribution,visible:false})]})]);
 await visitor();expect((await profile())?.events).toEqual([]);
 await actor(owner);await db.query("select lub.set_talent_contribution($1,true)",[contribution]);
 await visitor();expect((await profile())?.events).toHaveLength(1);
 await db.exec("reset role");await db.query("update lub.users set status_code='Inactive' where id=$1",[owner]);await actor(owner);
 expect((await db.query<{data:unknown}>("select lub.talent_workspace() as data")).rows[0].data).toEqual({status:"Inactive",onboarded:false});
});
