import Link from "next/link";
import type {TaskDetail} from "./repository";
import {TaskForm} from "./task-form";
import {eventLabels,eventLabelsEn} from "@/features/events/display";
import type {Locale} from "@/lib/preferences";
export function TaskEventLink({detail:d,eventPage,query,locale="ar"}:{detail:TaskDetail;eventPage:number;query:Record<string,string>;locale?:Locale}){
 const en=locale==="en",c=(ar:string,english:string)=>en?english:ar,labels=en?eventLabelsEn:eventLabels;
 const choices=d.eventChoices,linked=d.linkedEvent,t=d.task,editable=d.canManage&&['Draft','Open'].includes(t.status_code);
 const href=(page:number)=>`/tasks/${t.id}?${new URLSearchParams({...query,eventPage:String(page)})}`;
 return <section className="panel space-y-4 p-6"><h2 className="text-xl font-semibold">{c("الفعالية المرتبطة","Linked event")}</h2>{linked?<Link href={`/events/${linked.id}`} className="text-link"><bdi>{linked.title}</bdi> · {labels[linked.status]}</Link>:<p className="text-muted">{t.event_id?c('تفاصيل الفعالية متاحة حسب صلاحية عرضها.','Event details are available according to your access.'):c('مهمة مستقلة.','Independent task.')}</p>}{editable&&<><TaskForm operation="link-event" fields={{task:t.id,revision:String(t.revision)}} label={c("حفظ ارتباط الفعالية","Save event link")} locale={locale}><label>{c("الفعالية","Event")}<select name="event" defaultValue={t.event_id??''}><option value="">{c("مهمة مستقلة","Independent task")}</option>{t.event_id&&!choices.slice(0,25).some(e=>e.id===t.event_id)&&<option value={t.event_id} dir="auto">{linked?.title??c('الفعالية الحالية','Current event')}</option>}{choices.slice(0,25).map(e=><option key={e.id} value={e.id} dir="auto">{e.title} · {labels[e.status]}</option>)}</select></label><p className="text-sm leading-7 text-muted">{c("الارتباط من نفس الجهة، ويحفظ نسخة ويبلغ المشاركين. لا يغيّر الحضور أو الساعات.","The linked event must belong to this organization. This saves a version and notifies participants without changing attendance or hours.")}</p></TaskForm><nav aria-label={c("صفحات اختيار الفعاليات","Event selection pages")} className="flex flex-wrap gap-4">{eventPage>0&&<Link className="text-link" href={href(eventPage-1)}>{c("فعاليات سابقة","Previous events")}</Link>}{choices.length>25&&<Link className="text-link" href={href(eventPage+1)}>{c("فعاليات أخرى","More events")}</Link>}</nav></>}</section>;
}
