import Link from "next/link";
import {formatTaskDate,formatTaskDateEn,taskLabels,taskLabelsEn} from "./display";
import type {TaskDetail} from "./repository";
import {TaskForm} from "./task-form";
import {TaskFields} from "./task-fields";
import {SubmissionForm} from "./submission-form";
import {TaskPagination} from "./task-list";
import {TaskEventLink} from "./event-link";
import type {Locale} from "@/lib/preferences";
export function TaskDetailView({detail:d,page,teamPage,participant,eventPage=0,locale="ar"}:{detail:TaskDetail;page:number;teamPage:number;participant:string|null;eventPage?:number;locale?:Locale}){
 const en=locale==="en",c=(ar:string,english:string)=>en?english:ar,labels=en?taskLabelsEn:taskLabels,date=en?formatTaskDateEn:formatTaskDate;
 const t=d.task;const editable=d.canManage&&["Draft","Open"].includes(t.status_code);const overdue=d.current&&t.status_code==="Open"&&t.due_at&&new Date(t.due_at)<new Date();const ownEditable=d.current&&t.status_code==="Open"&&d.own&&["Joined","In_Progress"].includes(d.own.status_code);
 const query={...(participant?{participant}:{}),teamPage:String(teamPage),eventPage:String(eventPage)};const teamUrl=(next:number)=>`/tasks/${t.id}?${new URLSearchParams({...query,page:String(page),teamPage:String(next)})}`;
 return <div className="space-y-8"><div><div className="mb-3 flex flex-wrap items-center gap-3"><span className="rounded-md bg-mist px-3 py-2 text-sm">{!d.current?c("نسخة من سجلك السابق","Copy from your earlier record"):overdue?labels.Overdue:labels[t.status_code]}</span><span className="text-sm text-muted">{c("نسخة المهمة","Task version")} {t.revision}</span></div><h1 dir="auto" className="break-words text-3xl leading-normal font-bold">{t.title}</h1></div>
 {!d.current&&<p className="panel p-5 leading-8">{c("هذه نسخة محفوظة من مشاركتك السابقة. تفاصيل الفريق والتغييرات اللاحقة متاحة للأعضاء الحاليين فقط.","This is a saved copy of your earlier participation. Team details and later changes are available only to current members.")}</p>}
 {d.current&&<TaskEventLink detail={d} eventPage={eventPage} query={{...query,page:String(page)}} locale={locale}/>}
 <section className="panel p-6"><h2 className="mb-4 text-xl font-semibold">{c("المطلوب","What to do")}</h2><p dir="auto" className="whitespace-pre-wrap break-words leading-8">{t.description}</p><dl className="mt-5 grid gap-4 sm:grid-cols-3"><div><dt className="text-sm text-muted">{c("بداية الانضمام","Joining starts")}</dt><dd>{date(t.starts_at)}</dd></div><div><dt className="text-sm text-muted">{c("موعد التسليم","Due date")}</dt><dd>{date(t.due_at)}</dd></div><div><dt className="text-sm text-muted">{c("الساعات المقترحة","Suggested hours")}</dt><dd>{t.default_hours}</dd></div></dl>{overdue&&<p className="mt-4 text-sm leading-7 text-muted">{c("تجاوزت الموعد، لكنها تظل مفتوحة حتى إغلاقها يدويًا.","The due date passed, but the task remains open until manually closed.")}</p>}</section>
 {editable&&<section className="panel space-y-6 p-6"><h2 className="text-xl font-semibold">{c("إدارة المهمة","Manage task")}</h2><details><summary className="cursor-pointer font-medium">{c("تعديل الوصف والمواعيد","Edit description and dates")}</summary><div className="mt-5"><TaskForm operation="save-task" fields={{task:t.id,org:t.organization_id,committee:t.committee_id??"",revision:String(t.revision)}} label={c("حفظ نسخة جديدة","Save new version")} locale={locale}><TaskFields value={t} locale={locale}/></TaskForm></div></details>
 <div className="grid gap-5 sm:grid-cols-2">{t.status_code==="Draft"&&<TaskForm operation="status" fields={{task:t.id,status:"Open",revision:String(t.revision)}} label={c("نشر المهمة","Publish task")} locale={locale}/>}{(t.status_code==="Draft"?["Cancelled"]:["Completed","Cancelled"]).map(status=><TaskForm key={status} operation="status" fields={{task:t.id,status,revision:String(t.revision)}} label={status==="Completed"?c("إكمال المهمة","Complete task"):c("إلغاء المهمة","Cancel task")} locale={locale}><label className="flex items-start gap-3"><input className="mt-1 size-5 shrink-0" type="checkbox" name="confirm" required/>{c("أؤكد إغلاق المهمة ومنع الانضمام والتسليمات والمراجعات الجديدة، مع حفظ السجل.","I confirm closing the task and blocking new joins, submissions and reviews while preserving the record.")}</label></TaskForm>)}</div></section>}
 <section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("مشاركتي","My participation")}</h2>{d.own?<><p>{c("الحالة","Status")}: {labels[d.own.status_code]}</p>{d.own.approved_hours_override!==null&&<p>{c("الساعات المحددة للمشاركة","Hours set for this participation")}: {d.own.approved_hours_override}{c("؛ ",". ")}{c("لم تُضف إلى رصيد الساعات بعد.","Not yet added to the hours balance.")}</p>}{ownEditable&&<>{d.own.status_code==="Joined"&&<TaskForm operation="start" fields={{participant:d.own.id}} label={c("بدء العمل","Start work")} locale={locale}/>}<SubmissionForm key={`${d.own.id}-${d.lastRevision}`} participant={d.own.id} revision={t.revision} lastRevision={d.lastRevision} locale={locale}/></>}</>:d.current&&t.status_code==="Open"&&(!t.starts_at||new Date(t.starts_at)<=new Date())?<TaskForm operation="join" fields={{task:t.id}} label={c("الانضمام للمهمة","Join task")} locale={locale}/>:<p className="text-muted">{c("الانضمام غير متاح الآن.","Joining is unavailable now.")}</p>}</section>
 {d.current&&<section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("فريق المهمة","Task team")}</h2><p className="text-sm leading-7 text-muted">{c("المخرجات والمرفقات متاحة لصاحب المشاركة والمراجع المخوّل فقط.","Deliverables and attachments are available only to their participant and authorized reviewers.")}</p>{d.team.length?<ul className="divide-y divide-line">{d.team.slice(0,100).map(p=><li key={p.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><span><bdi>{p.name}</bdi> · {labels[p.status]}</span>{d.canManage&&<Link className="text-link" href={`/tasks/${t.id}?participant=${p.id}&teamPage=${teamPage}`}>{c("مراجعة المشاركة","Review participation")}</Link>}</li>)}</ul>:<p>{c("لم ينضم أحد بعد.","No one has joined yet.")}</p>}<nav aria-label={c("صفحات فريق المهمة","Task team pages")} className="flex flex-wrap gap-4">{teamPage>0&&<Link className="text-link" href={teamUrl(teamPage-1)}>{c("الفريق السابق","Previous team page")}</Link>}{d.team.length>100&&<Link className="text-link" href={teamUrl(teamPage+1)}>{c("الفريق التالي","Next team page")}</Link>}</nav></section>}
 <section className="space-y-5"><div className="flex flex-wrap items-center gap-4"><h2 className="text-xl font-semibold">{participant&&d.canManage?c("تسليمات المشاركة المختارة","Selected participant submissions"):c("تسليماتي","My submissions")}</h2>{participant&&<Link className="text-link" href={`/tasks/${t.id}`}>{c("عرض تسليماتي","View my submissions")}</Link>}</div>
 {d.selected&&<p>{c("حالة المشاركة","Participation status")}: {labels[d.selected.status_code]}</p>}{d.submissions.length?d.submissions.slice(0,20).map(s=><article key={s.id} className="panel space-y-4 p-6"><h3 className="font-semibold">{c("تسليم","Submission")} {s.revision_number} · {labels[s.status_code]}</h3><p className="text-sm text-muted">{date(s.submitted_at)} · {c("نسخة المهمة","Task version")} {s.task_revision_number}</p><p dir="auto" className="whitespace-pre-wrap break-words leading-8">{s.message}</p><ul className="space-y-3">{s.assets.map(a=><li key={a.id}><a className="text-link break-all" href={`/files/${a.id}`} dir="auto">{a.name}</a></li>)}</ul>{s.review_note&&<p className="rounded-lg bg-mist p-4 whitespace-pre-wrap break-words leading-8">{c("ملاحظة المراجعة","Review note")}: <span dir="auto">{s.review_note}</span></p>}<details><summary className="cursor-pointer font-medium">{c("وصف المهمة وقت التسليم","Task description at submission")}</summary><p dir="auto" className="mt-4 whitespace-pre-wrap break-words leading-8">{s.task_snapshot.description}</p><p className="mt-3 text-sm text-muted">{c("الموعد","Due")}: {date(s.task_snapshot.due_at)} · {c("الساعات المقترحة","Suggested hours")}: {s.task_snapshot.default_hours}</p></details>
 {d.canManage&&t.status_code==="Open"&&s.status_code==="Submitted"&&d.selected?.status_code==="Submitted"&&<TaskForm operation="review" fields={{submission:s.id}} label={c("حفظ قرار المراجعة","Save review decision")} locale={locale}><label>{c("القرار","Decision")}<select name="status"><option value="Approved">{c("اعتماد المخرج","Approve deliverable")}</option><option value="Rejected">{c("طلب تعديل وإعادة تسليم","Request changes and resubmission")}</option></select></label><label>{c("ملاحظة المراجعة","Review note")}<textarea name="note" maxLength={3000} rows={3}/></label><p className="text-sm text-muted">{c("الملاحظة مطلوبة عند رفض النسخة.","A note is required when rejecting a version.")}</p><label>{c("ساعات المشاركة عند الاعتماد (اختياري)","Participation hours on approval (optional)")}<input name="hours" type="number" min={0} max={1000} step="0.01"/></label></TaskForm>}</article>):<p className="panel p-6 text-muted">{c("لا توجد تسليمات متاحة هنا.","No submissions available here.")}</p>}
 {d.canManage&&t.status_code==="Open"&&d.selected&&["Joined","In_Progress","Submitted"].includes(d.selected.status_code)&&<TaskForm operation="close" fields={{participant:d.selected.id}} label={c("إغلاق هذه المشاركة","Close this participation")} locale={locale}><label className="flex items-start gap-3"><input className="mt-1 size-5 shrink-0" type="checkbox" name="confirm" required/>{c("أؤكد إغلاق هذه المشاركة فقط وحفظ تسليماتها السابقة.","I confirm closing only this participation while preserving its earlier submissions.")}</label></TaskForm>}</section>
 <section className="panel space-y-4 p-6"><h2 className="text-xl font-semibold">{c("سجل نسخ المهمة","Task version history")}</h2>{d.history.slice(0,20).map(r=><details key={r.id}><summary className="cursor-pointer leading-8">{c("نسخة","Version")} {r.revision_number} · {date(r.changed_at)} · {labels[r.snapshot_json.status_code]}</summary><p dir="auto" className="mt-3 whitespace-pre-wrap break-words leading-8">{r.snapshot_json.description}</p><p className="mt-3 text-sm text-muted">{c("الموعد","Due")}: {date(r.snapshot_json.due_at)} · {c("الساعات المقترحة","Suggested hours")}: {r.snapshot_json.default_hours}</p></details>)}</section>
 <TaskPagination page={page} more={d.submissions.length>20||d.history.length>20} base={`/tasks/${t.id}`} query={query} locale={locale}/></div>;
}
