import {redirect} from "next/navigation";
import {HoursForm} from "./form";
import type {AccountReadiness,HourRecord,Term} from "./repository";
import type {Locale} from "@/lib/preferences";
export const hourLabels:Record<string,string>={Pending:"بانتظار الاعتماد",Approved:"معتمدة",Rejected:"مرفوضة",Voided:"مبطلة",TASK:"مهمة",MANUAL:"إضافة يدوية",SELF_REPORTED:"طلب ذاتي",Draft:"مسودة",Open:"مفتوحة",Closed:"مغلقة",Archived:"مؤرشفة",Renewed:"جدد العضوية",Declined:"رفض التجديد",No_Response:"لم يرد"};
export const hourLabelsEn:Record<string,string>={Pending:"Pending approval",Approved:"Approved",Rejected:"Rejected",Voided:"Voided",TASK:"Task",MANUAL:"Manual entry",SELF_REPORTED:"Self-reported",Draft:"Draft",Open:"Open",Closed:"Closed",Archived:"Archived",Renewed:"Renewed membership",Declined:"Declined renewal",No_Response:"No response"};
export function checkReadiness(value:AccountReadiness|undefined){if(value?.status==="Inactive")redirect("/account-unavailable");if(!value?.onboarded)redirect("/onboarding");}
export function TermSelect({terms,value,all=false,locale="ar"}:{terms:Term[];value?:string;all?:boolean;locale?:Locale}){const en=locale==="en";return <label>{en?"Academic term":"الفصل الأكاديمي"}<select name="term" required={!all} defaultValue={value??""}><option value="">{all?en?"All terms":"كل الفصول":en?"Choose term":"اختر الفصل"}</option>{terms.map(t=><option key={t.id} value={t.id} dir="auto">{t.name_ar} · {t.academic_year} ({t.start_date} — {t.end_date})</option>)}</select></label>;}
export function HoursFields({terms,locale="ar"}:{terms:Term[];locale?:Locale}){const en=locale==="en";return <><TermSelect terms={terms} locale={locale}/><label>{en?"Work date":"تاريخ العمل"}<input type="date" name="day" required/></label><label>{en?"Hours":"عدد الساعات"}<input type="number" name="hours" min={0} max={1000} step="0.01" required/></label><label>{en?"Work description and reason for entry":"وصف العمل وسبب الإضافة"}<textarea name="reason" required maxLength={3000} rows={3}/></label></>;}
export function HoursList({items,locale="ar"}:{items:HourRecord[];locale?:Locale}){const en=locale==="en",labels=en?hourLabelsEn:hourLabels,c=(ar:string,english:string)=>en?english:ar;return items.length?<ul className="space-y-4">{items.slice(0,25).map(h=><li key={h.id} className="panel min-w-0 space-y-4 p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold break-words"><bdi>{h.owner??c("سجل الساعات","Hours record")}</bdi> · {h.hours} {c("ساعة","hours")}</h2><span className="text-sm text-muted">{labels[h.status_code]}</span></div><p className="text-sm leading-7 text-muted"><bdi>{h.org_name}</bdi> · <bdi>{h.term_name}</bdi> · {h.activity_date} · {labels[h.source_code]}</p><p dir="auto" className="whitespace-pre-wrap break-words leading-8">{h.description}</p>{h.decisions.map((d,i)=><p key={i} className="whitespace-pre-wrap break-words text-sm leading-7">{labels[d.status_code]}{d.note&&<>: <span dir="auto">{d.note}</span></>}</p>)}{h.canReview&&["Pending","Approved"].includes(h.status_code)&&<details><summary className="cursor-pointer font-medium">{h.status_code==="Approved"?c("إبطال السجل للتصحيح","Void record for correction"):c("مراجعة الساعات","Review hours")}</summary><div className="mt-4"><HoursForm operation="review" fields={{record:h.id,...(h.status_code==="Approved"?{status:"Voided"}:{})}} label={c("حفظ القرار","Save decision")} locale={locale}>{h.status_code==="Pending"&&<label>{c("القرار","Decision")}<select name="status"><option value="Approved">{c("اعتماد","Approve")}</option><option value="Rejected">{c("رفض","Reject")}</option></select></label>}<label>{c("سبب القرار","Reason for decision")}<textarea name="note" maxLength={3000} rows={3} required={h.status_code==="Approved"}/></label><p className="text-sm leading-7 text-muted">{c("الرفض والإبطال يتطلبان سببًا. التصحيح يحفظ السجل، ويحتاج إضافة جديدة بالقيمة الصحيحة.","Rejection and voiding require a reason. The original record remains in history; add a new record with the correct value.")}</p>{h.status_code==="Approved"&&<label className="flex items-center gap-3"><input type="checkbox" name="confirm" required className="size-5"/>{c("أؤكد إبطال الساعات","I confirm voiding these hours")}</label>}</HoursForm></div></details>}</li>)}</ul>:<p className="panel p-6 leading-8 text-muted">{c("لا توجد سجلات ساعات لهذه الفترة.","No hours records for this period.")}</p>;}
