import Link from "next/link";
import {HoursForm} from "./form";
import {HoursFields,HoursList,TermSelect} from "./view";
import type {HoursData,HoursWorkspace,HourRule} from "./repository";
import {TaskPagination} from "@/features/tasks/task-list";
import {DateInput} from "@/features/forms/date-input";
import type {Locale} from "@/lib/preferences";
export type HoursFilters={term:string|null;committee:string|null;page:number;memberPage:number;rulePage:number};
const capabilityLabels:Record<string,string>={HOURS_APPROVE:"اعتماد وإبطال الساعات",HOURS_MANUAL_ADD:"إضافة ساعات يدوية",HOUR_RULES_MANAGE:"إدارة قواعد الساعات",RENEWALS_MANAGE:"إدارة التجديد"};
const capabilityLabelsEn:Record<string,string>={HOURS_APPROVE:"Approve and void hours",HOURS_MANUAL_ADD:"Add hours manually",HOUR_RULES_MANAGE:"Manage hours rules",RENEWALS_MANAGE:"Manage renewals"};
export function PersonalHoursView({data,page,term,locale="ar"}:{data:HoursData;page:number;term:string|null;locale?:Locale}){const en=locale==="en",c=(ar:string,english:string)=>en?english:ar;return <div className="space-y-8"><div><h1 className="text-3xl font-bold">{c("ساعاتي","My hours")}</h1><p className="mt-3 leading-8 text-muted">{c("الرصيد يحتسب الساعات المعتمدة فقط، ويحفظ السجلات السابقة بعد انتهاء العضوية.","The balance includes approved hours only. Earlier records remain after a membership ends.")}</p></div><form className="panel flex flex-wrap items-end gap-4 p-5"><div className="min-w-0 flex-1"><TermSelect terms={data.terms} all value={term??""} locale={locale}/></div><button className="button button-secondary">{c("عرض الفترة","Show period")}</button></form><section className="panel p-6"><h2 className="text-xl font-semibold">{c("الرصيد المعتمد","Approved balance")}: {data.total} {c("ساعة","hours")}</h2><ul className="mt-4 space-y-3">{data.byOrg.map((x,i)=><li key={i} className="break-words"><bdi>{x.name}</bdi> · {x.total} {c("ساعة","hours")}</li>)}</ul></section><HoursList items={data.records} locale={locale}/><TaskPagination page={page} more={data.records.length>25} base="/hours" query={term?{term}:{}} locale={locale}/>{data.memberships.filter(m=>m.self).map(m=><details key={m.id} className="panel p-6"><summary className="cursor-pointer font-semibold">{c("طلب ساعات ذاتي","Self-reported hours request")} · <bdi>{m.name}</bdi></summary><div className="mt-5"><HoursForm operation="self" fields={{member:m.id}} label={c("إرسال للمراجعة","Submit for review")} locale={locale}><label>{c("نطاق العمل","Work scope")}<select name="committee"><option value="">{c("الجهة بالكامل","Whole organization")}</option>{m.committees.map(item=><option key={item.id} value={item.id} dir="auto">{item.name}</option>)}</select></label><HoursFields terms={data.terms} locale={locale}/></HoursForm></div></details>)}</div>;}
export function HoursWorkspaceView({data,org,filters,locale="ar"}:{data:HoursWorkspace;org:string;filters:HoursFilters;locale?:Locale}){
 const en=locale==="en",c=(ar:string,english:string)=>en?english:ar,labels=en?capabilityLabelsEn:capabilityLabels;
 const base=`/manage/organizations/${org}/hours`;const {term,committee,page,memberPage,rulePage}=filters;
 const query={...(term?{term}:{}),...(committee?{committee}:{}),memberPage:String(memberPage),rulePage:String(rulePage)};
 const selected=data.scopes.find(s=>s.id===committee);const options=(key:"manual"|"rules")=>data.scopes.filter(s=>s[key]);
 const scopeSelect=(key:"manual"|"rules")=><label>{c("النطاق","Scope")}<select name="committee" defaultValue={committee??""}>{options(key).map(s=><option key={s.id??"org"} value={s.id??""} dir="auto">{s.name}</option>)}</select></label>;
 const memberSelect=<label>{c("العضو","Member")}<select name="member" required><option value="">{c("اختر العضو","Choose member")}</option>{data.members.slice(0,25).map(m=><option key={m.id} value={m.id} dir="auto">{m.name}</option>)}</select></label>;
 const ruleFields=(r?:HourRule)=><><label>{c("اسم القاعدة","Rule name")}<input name="name" required minLength={2} maxLength={120} defaultValue={r?.name??""}/></label><label>{c("الساعات الافتراضية","Default hours")}<input name="hours" type="number" min={0} max={1000} step="0.01" required defaultValue={r?.default_hours??"0"}/></label><div className="grid gap-4 sm:grid-cols-2"><label>{c("تسري من","Effective from")}<input type="date" name="starts" required defaultValue={r?.effective_from??""}/></label><label>{c("إلى (اختياري)","Until (optional)")}<input type="date" name="ends" defaultValue={r?.effective_to??""}/></label></div><label className="flex items-center gap-3"><input name="active" type="checkbox" className="size-5" defaultChecked={r?.is_active??true}/>{c("قاعدة نشطة","Active rule")}</label></>;
 return <div className="space-y-8"><div><Link className="text-link mb-4 inline-block" href={`/manage/organizations/${org}`}>{c("إدارة الجهة","Manage organization")}</Link><h1 className="text-3xl leading-normal font-bold">{c("ساعات","Hours for")} <bdi>{data.name}</bdi></h1><p className="mt-3 leading-8 text-muted">{c("اعتماد الساعات وتصحيحها، بقواعد ونطاقات واضحة.","Approve and correct hours with clear rules and scopes.")}</p></div><form className="panel grid gap-4 p-5 sm:grid-cols-2"><TermSelect terms={data.terms} all value={term??""} locale={locale}/><label>{c("اللجنة","Committee")}<select name="committee" defaultValue={committee??""}><option value="">{c("كل النطاقات المتاحة","All available scopes")}</option>{data.scopes.filter(s=>s.id).map(s=><option key={s.id} value={s.id!} dir="auto">{s.name}</option>)}</select></label><button className="button button-secondary sm:col-span-2">{c("عرض السجلات","Show records")}</button></form><p className="text-xl font-semibold">{c("الساعات المعتمدة ضمن العرض","Approved hours in this view")}: {data.total}</p><HoursList items={data.records} locale={locale}/><TaskPagination page={page} more={data.records.length>25} base={base} query={query} locale={locale}/>
 {selected?.manual&&data.members.length>0&&<details className="panel p-6"><summary className="cursor-pointer font-semibold">{c("إضافة ساعات يدوية","Add hours manually")}</summary><div className="mt-5"><HoursForm operation="add" fields={{committee:committee??""}} label={c("إضافة الساعات","Add hours")} locale={locale}>{memberSelect}<HoursFields terms={data.terms} locale={locale}/><p className="text-sm leading-7 text-muted">{selected.approve?c("تُعتمد الإضافة مباشرة ضمن صلاحيتك.","This entry is approved immediately under your permission."):c("تُرسل الإضافة لمراجعة المخوّل بالاعتماد.","This entry is sent to an authorized reviewer.")}</p></HoursForm></div></details>}
 {options("manual").length>0&&<div className="panel space-y-4 p-5"><p className="leading-7 text-muted">{c("اختر اللجنة أعلاه لإظهار أعضائها. الإضافة للجهة بالكامل متاحة لقيادتها والمفوّضين بها.","Choose a committee above to see its members. Organization-wide entries are available to leaders and authorized members.")}</p><nav aria-label={c("صفحات الأعضاء","Member pages")} className="flex flex-wrap gap-4">{memberPage>0&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,page:String(page),memberPage:String(memberPage-1)})}`}>{c("السابق","Previous")}</Link>}{(data.members.length>25||data.grants.length>25)&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,page:String(page),memberPage:String(memberPage+1)})}`}>{c("التالي","Next")}</Link>}</nav></div>}
 {data.imports.length>0&&<section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("مشاركات معتمدة سابقة بلا سجل ساعات","Earlier approved participation without an hours record")}</h2><p className="text-sm leading-7 text-muted">{c("الاستيراد يستخدم نسخة التسليم وتاريخ الاعتماد، ويتطلب فصلًا يغطي ذلك التاريخ.","Import uses the submitted copy and approval date. A term must cover that date.")}</p>{data.imports.map(p=><div key={p.id}><p dir="auto" className="mb-3">{p.name}</p><HoursForm operation="import" fields={{participant:p.id}} label={c("استيراد ساعات المشاركة","Import participation hours")} locale={locale}/></div>)}</section>}
 <section className="space-y-5"><h2 className="text-xl font-semibold">{c("قواعد الساعات","Hours rules")}</h2>{data.rules.slice(0,25).map(r=><article key={r.id} className="panel space-y-4 p-6"><h3 className="font-semibold"><bdi>{r.name}</bdi> · {r.default_hours} {c("ساعة","hours")}</h3><p className="text-sm leading-7 text-muted">{r.is_active?c("نشطة","Active"):c("موقوفة","Paused")} · {r.effective_from}{r.effective_to&&` ${c("إلى","to")} ${r.effective_to}`}</p>{r.canEdit&&<details><summary className="cursor-pointer">{c("تعديل القاعدة","Edit rule")}</summary><div className="mt-5"><HoursForm operation="rule" fields={{org,rule:r.id,committee:r.committee_id??"",template:r.task_template_id??"",revision:String(r.revision)}} label={c("حفظ القاعدة","Save rule")} locale={locale}>{ruleFields(r)}</HoursForm></div></details>}</article>)}{!data.rules.length&&<p className="panel p-6 text-muted">{c("لا توجد قواعد في هذا النطاق.","No rules in this scope.")}</p>}<nav aria-label={c("صفحات القواعد","Rule pages")} className="flex flex-wrap gap-4">{rulePage>0&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,rulePage:String(rulePage-1)})}`}>{c("القواعد السابقة","Previous rules")}</Link>}{data.rules.length>25&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,rulePage:String(rulePage+1)})}`}>{c("قواعد أخرى","More rules")}</Link>}</nav>
 {options("rules").length>0&&<details className="panel p-6"><summary className="cursor-pointer font-semibold">{c("قاعدة ساعات جديدة","New hours rule")}</summary><div className="mt-5"><HoursForm operation="rule" fields={{org}} label={c("إنشاء القاعدة","Create rule")} locale={locale}>{scopeSelect("rules")}<label>{c("قالب المهمة (اختياري)","Task template (optional)")}<select name="template"><option value="">{c("قاعدة عامة للنطاق","General rule for scope")}</option>{data.templates.map(t=><option key={t.id} value={t.id} dir="auto">{t.name}</option>)}</select></label>{ruleFields()}</HoursForm></div></details>}</section>
 {data.canPolicy&&<details className="panel p-6"><summary className="cursor-pointer font-semibold">{c("سياسة طلب الساعات الذاتي","Self-reported hours policy")}</summary><div className="mt-5"><HoursForm operation="self-policy" fields={{org}} label={c("حفظ السياسة","Save policy")} locale={locale}><label className="flex items-center gap-3"><input type="checkbox" name="enabled" className="size-5" defaultChecked={data.selfEnabled}/>{c("السماح للأعضاء بطلب ساعات للمراجعة","Allow members to submit hours for review")}</label></HoursForm></div></details>}
 {data.canGrant&&<section className="panel space-y-5 p-6"><h2 className="text-xl font-semibold">{c("تفويض صلاحيات الساعات والتجديد","Hours and renewals permissions")}</h2>{data.members.length>0&&<HoursForm operation="grant" label={c("منح الصلاحية","Grant permission")} locale={locale}>{memberSelect}<label>{c("الصلاحية","Permission")}<select name="capability">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>{c("النطاق","Scope")}<select name="committee"><option value="">{c("الجهة بالكامل","Whole organization")}</option>{data.scopes.filter(s=>s.id).map(s=><option key={s.id} value={s.id!} dir="auto">{s.name}</option>)}</select></label><p className="text-sm text-muted">{c("إدارة التجديد تُفوّض على الجهة بالكامل.","Renewals management is granted for the whole organization.")}</p><DateInput name="ends" label={c("انتهاء التفويض (اختياري)","Permission ends (optional)")} locale={locale}/></HoursForm>}{data.grants.slice(0,25).map(g=><div key={g.id} className="border-t border-line pt-5"><p className="mb-3"><bdi>{g.name}</bdi> · {labels[g.permission_code]} · <bdi>{data.scopes.find(s=>s.id===g.committee_id)?.name??c("نطاق لجنة","Committee scope")}</bdi></p><HoursForm operation="end-grant" fields={{grant:g.id}} label={c("إنهاء التفويض","End permission")} locale={locale}><label className="flex items-center gap-3"><input type="checkbox" name="confirm" className="size-5" required/>{c("أؤكد إنهاء التفويض","I confirm ending this permission")}</label></HoursForm></div>)}</section>}</div>;
}
