import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { requireManagementUser } from "@/features/organizations/access";
import { getManagementOrganization } from "@/features/organizations/management-repository";
import { MutationForm } from "@/features/organizations/mutation-form";
import { OrganizationTextFields, CommitteeFields } from "@/features/organizations/form-fields";
import {getPreferences} from "@/lib/preferences";

export async function generateMetadata(){return localizedMetadata('إدارة الجهة','Manage organization');}
export default async function ManageOrganizationPage({ params }: { params: Promise<{ id: string }> }) {
  const locale=(await getPreferences()).locale;const en=locale==="en";
  const user = await requireManagementUser();
  const { id } = await params;
  if (!z.uuid().safeParse(id).success) notFound();
  let managed: Awaited<ReturnType<typeof getManagementOrganization>>;
  try { managed = await getManagementOrganization(user.id, id); }
  catch { throw new Error("Management storage is unavailable."); }
  if (!managed) notFound();
  const { organization, committees } = managed;
  return <>
    <div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><h1 dir="auto" className="text-3xl leading-normal font-bold">{organization.nameAr}</h1><p className="mt-3 leading-8 text-muted">{en?"Organization and committee settings available within your permissions.":"إعدادات الجهة واللجان المتاحة ضمن صلاحياتك."}</p></div><Link href={`/organizations/${organization.slug}`} className="button button-secondary">{en?"Public page":"الصفحة العامة"}</Link>{organization.canApplications&&<Link href={`/manage/organizations/${id}/applications`} className="button">{en?"Forms and applications":"النماذج وطلبات الانضمام"}</Link>}{organization.canEvents&&<Link href={`/manage/organizations/${id}/events`} className="button">{en?"Events":"الفعاليات"}</Link>}{organization.canReports&&<Link href={`/manage/organizations/${id}/documents`} className="button">{en?"Reports and documents":"التقارير والمستندات"}</Link>}{organization.canHours&&<Link href={`/manage/organizations/${id}/hours`} className="button">{en?"Hours and rules":"الساعات والقواعد"}</Link>}{organization.canRenewals&&<Link href={`/manage/organizations/${id}/renewals`} className="button">{en?"Renewals":"التجديد"}</Link>}{organization.canTasks&&<Link href={`/manage/organizations/${id}/tasks`} className="button">{en?"Tasks and templates":"المهام والقوالب"}</Link>}</div>
    {organization.canEdit && <section className="panel mb-8 p-6 sm:p-8" aria-labelledby="profile-title"><h2 id="profile-title" className="mb-6 text-xl font-semibold">{en?"Organization profile":"بيانات الجهة"}</h2><MutationForm operation="org-profile" fields={{ organizationId: id }} submitLabel={en?"Save organization profile":"حفظ بيانات الجهة"} locale={locale}><OrganizationTextFields prefix="edit" value={organization} locale={locale}/><div><label htmlFor="edit-tags">{en?"Interests":"مجالات الاهتمام"}</label><input id="edit-tags" name="tagNames" dir="auto" maxLength={500} defaultValue={managed.tagNames} aria-describedby="tags-help" /><p id="tags-help" className="mt-2 text-sm leading-7 text-muted">{en?"Separate interests with commas. Up to ten interests.":"افصل المجالات بفاصلة. عشرة مجالات كحد أقصى."}</p></div><div><label htmlFor="edit-website">{en?"Website or contact URL":"رابط الموقع أو التواصل"}</label><input id="edit-website" name="websiteUrl" type="url" dir="ltr" maxLength={2048} defaultValue={managed.websiteUrl} placeholder="https://" /><p className="mt-2 text-sm leading-7 text-muted">{en?"Optional HTTPS link shown on the public page.":"رابط HTTPS اختياري يظهر في الصفحة العامة."}</p></div><div><label htmlFor="edit-logo">{en?"Logo URL":"رابط الشعار"}</label><input id="edit-logo" name="logoUrl" type="url" dir="ltr" maxLength={2048} defaultValue={organization.logoUrl} placeholder="https://" /><p className="mt-2 text-sm leading-7 text-muted">{en?"Direct HTTPS link to the logo image. Leave blank if no logo is available.":"رابط HTTPS مباشر لصورة الشعار. اتركه فارغًا إذا لم يتوفر شعار."}</p></div><label className="mb-0 flex items-center gap-3"><input type="checkbox" name="showLeadershipPublicly" defaultChecked={organization.showLeadershipPublicly} className="size-5 shrink-0 accent-action" />{en?"Show leadership publicly":"إظهار قيادة الجهة للعامة"}</label></MutationForm></section>}
    {organization.canEdit && <section className="panel mb-8 p-6 sm:p-8" aria-labelledby="announcements-title"><h2 id="announcements-title" className="text-xl font-semibold">{en?"Announcements":"إعلانات الجهة"}</h2><p className="mt-2 text-sm leading-7 text-muted">{en?"Published announcements are visible to visitors. One announcement can be pinned at the top.":"تظهر الإعلانات المنشورة للزوار بدون تسجيل دخول. يمكن تثبيت إعلان واحد في أعلى القائمة."}</p><div className="mt-6"><MutationForm operation="save-announcement" fields={{organizationId:id}} submitLabel={en?"Save new announcement":"حفظ إعلان جديد"} locale={locale}><div><label htmlFor="new-announcement-title">{en?"Title":"العنوان"}</label><input id="new-announcement-title" name="title" dir="auto" minLength={2} maxLength={120} required /></div><div><label htmlFor="new-announcement-body">{en?"Text":"النص"}</label><textarea id="new-announcement-body" name="body" dir="auto" rows={4} maxLength={5000} required /></div><label className="flex items-center gap-3"><input type="checkbox" name="published" className="size-5" />{en?"Publish publicly":"نشر للعامة"}</label><label className="flex items-center gap-3"><input type="checkbox" name="pinned" className="size-5" />{en?"Pin announcement":"تثبيت الإعلان"}</label></MutationForm></div>{organization.announcements.length>0&&<ul className="mt-8 divide-y divide-line">{organization.announcements.map(a=><li key={a.id} className="py-5"><details><summary className="cursor-pointer font-medium"><bdi>{a.title}</bdi> — {en?a.published?"Published":"Draft":a.published?"منشور":"مسودة"}{a.pinned?en?" · Pinned":" · مثبّت":""}</summary><div className="mt-5"><MutationForm operation="save-announcement" fields={{organizationId:id,announcementId:a.id}} submitLabel={en?"Save changes":"حفظ التعديل"} locale={locale}><div><label htmlFor={`announcement-title-${a.id}`}>{en?"Title":"العنوان"}</label><input id={`announcement-title-${a.id}`} name="title" dir="auto" minLength={2} maxLength={120} defaultValue={a.title} required /></div><div><label htmlFor={`announcement-body-${a.id}`}>{en?"Text":"النص"}</label><textarea id={`announcement-body-${a.id}`} name="body" dir="auto" rows={4} maxLength={5000} defaultValue={a.body} required /></div><label className="flex items-center gap-3"><input type="checkbox" name="published" defaultChecked={a.published} className="size-5" />{en?"Publish publicly":"نشر للعامة"}</label><label className="flex items-center gap-3"><input type="checkbox" name="pinned" defaultChecked={a.pinned} className="size-5" />{en?"Pin announcement":"تثبيت الإعلان"}</label></MutationForm><div className="mt-5"><MutationForm operation="archive-announcement" fields={{organizationId:id,announcementId:a.id}} submitLabel={en?"Archive announcement":"أرشفة الإعلان"} confirmLabel={en?"I confirm archiving and hiding this announcement from the public page":"أؤكد أرشفة الإعلان وإخفاءه عن الصفحة العامة"} locale={locale}/></div></div></details></li>)}</ul>}</section>}
    <section aria-labelledby="committees-title"><h2 id="committees-title" className="mb-5 text-xl font-semibold">{en?"Committees":"اللجان"}</h2><div className="space-y-5">{committees.map(committee => <section key={committee.id} className="panel p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h3 dir="auto" className="text-lg font-semibold">{committee.name}</h3><span className="text-sm text-muted">{en?committee.statusCode==="Archived"?"Archived":committee.isPublic?"Public":"Internal":committee.statusCode === "Archived" ? "مؤرشفة" : committee.isPublic ? "ظاهرة للعامة" : "داخلية"}</span></div>
      {committee.statusCode === "Active" && committee.canEdit && <details><summary className="cursor-pointer font-medium">{en?"Edit committee details":"تعديل بيانات اللجنة"}</summary><div className="mt-5"><MutationForm operation="save-committee" fields={{ organizationId: id, committeeId: committee.id }} submitLabel={en?"Save committee":"حفظ اللجنة"} locale={locale}><CommitteeFields prefix={committee.id} value={committee} locale={locale}/></MutationForm></div></details>}
      {organization.canManageCommittees && <div className="mt-5 border-t border-line pt-5"><details><summary className="cursor-pointer text-sm font-medium">{en?"Copy committee or change its status":"نسخ اللجنة أو تغيير حالتها"}</summary><div className="mt-5 space-y-5"><MutationForm operation="copy-committee" fields={{ organizationId: id, committeeId: committee.id }} submitLabel={en?"Copy committee details":"نسخ بيانات اللجنة"} locale={locale}/><MutationForm operation="committee-status" fields={{ organizationId: id, committeeId: committee.id, status: committee.statusCode === "Archived" ? "Active" : "Archived" }} submitLabel={en?committee.statusCode==="Archived"?"Restore committee":"Archive committee":committee.statusCode === "Archived" ? "استعادة اللجنة" : "أرشفة اللجنة"} confirmLabel={en?committee.statusCode==="Archived"?"I confirm restoring this committee":"I confirm archiving this committee while preserving its history":committee.statusCode === "Archived" ? "أؤكد استعادة هذه اللجنة" : "أؤكد أرشفة اللجنة مع حفظ تاريخها"} locale={locale}/></div></details></div>}
    </section>)}{committees.length === 0 && <p className="panel p-6 leading-8 text-muted">{en?"No committees are available within your permissions.":"لا توجد لجان متاحة لإدارتها ضمن صلاحياتك."}</p>}</div></section>
    {organization.canManageCommittees && <section className="panel mt-8 p-6 sm:p-8" aria-labelledby="new-committee-title"><h2 id="new-committee-title" className="mb-6 text-xl font-semibold">{en?"Add committee":"إضافة لجنة"}</h2><MutationForm operation="save-committee" fields={{ organizationId: id }} submitLabel={en?"Create committee":"إنشاء اللجنة"} locale={locale}><CommitteeFields prefix="new-committee" locale={locale}/></MutationForm></section>}
  </>;
}
