import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { z } from "zod";
import { requireUser } from "@/features/auth/session";
import { getWorkspace,listApplications,statuses,capabilities,type Filters } from "@/features/forms/repository";
import { WorkflowForm } from "@/features/forms/mutation-form";
import { FormEditor } from "@/features/forms/editor";
import { ApplicationSelection } from "@/features/forms/application-selection";
import { DateInput } from "@/features/forms/date-input";
import { cookies } from "next/headers";
import { decryptIdentifier } from "@/lib/identifiers";
import { searchApplications } from "@/features/forms/search-action";
import {getPreferences} from "@/lib/preferences";
export async function generateMetadata(){return localizedMetadata('النماذج وطلبات الانضمام','Forms and applications');}
export default async function WorkflowPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const [user,{locale}]=await Promise.all([requireUser(),getPreferences()]);const en=locale==="en";const c=(ar:string,english:string)=>en?english:ar;const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();
 const search=await searchParams;
 const value=(key:string)=>typeof search[key]==="string"?search[key] as string:"";
 let lookup="";try{const saved=(await cookies()).get("lub-application-search")?.value;if(saved){const hash=decryptIdentifier(saved,`application-search:${user.id}:${id}`);if(/^[a-f0-9]{64}$/.test(hash))lookup=hash;}}catch{}
 const filters:Filters={q:value("q").slice(0,120),status:["Submitted","Interview","Accepted","Rejected","Withdrawn"].includes(value("status"))?value("status"):"",committee:z.uuid().safeParse(value("committee")).success?value("committee"):"",major:value("major").slice(0,120),level:value("level").slice(0,20),from:z.iso.date().safeParse(value("from")).success?value("from"):"",to:z.iso.date().safeParse(value("to")).success?value("to"):"",page:Math.min(1000,Math.max(1,Math.floor(Number(value("page"))||1))),lookup,activity:["prior","first"].includes(value("activity"))?value("activity"):""};
 const [workspace,rows]=await Promise.all([getWorkspace(user.id,id,z.uuid().safeParse(search.template).success?search.template as string:null),listApplications(user.id,id,filters)]);
 if(workspace?.accountStatus==="Inactive")redirect("/account-unavailable");if(workspace&&!workspace.onboarded)redirect("/onboarding");if(!workspace?.allowed.length)notFound();const allowed=(code:string)=>workspace.allowed.includes(code);
 const own=workspace.templates.filter(t=>t.organization_id===id);
 const selected=own.find(t=>t.id===value("template"));
 const version=selected?.versions.find(v=>v.status_code==="Draft")??selected?.versions[0];
 function pageHref(page:number){const query=new URLSearchParams();for(const key of ["q","status","committee","major","level","from","to","activity"])if(value(key))query.set(key,value(key));query.set("page",String(page));return "?"+query;}
 return <><Link href={`/manage/organizations/${id}`} className="text-link">{c("إدارة الجهة","Organization management")}</Link><h1 dir="auto" className="mt-5 text-3xl font-bold">{workspace.name}</h1><p className="mt-3 mb-8 text-muted leading-8">{c("النماذج وجولات التسجيل وطلبات الانضمام ضمن صلاحياتك.","Forms, registration rounds, and applications within your permissions.")}</p>
 {allowed("FORMS_MANAGE")&&<section className="panel mb-6 p-6"><h2 className="mb-5 text-xl font-semibold">{c("النماذج","Forms")}</h2><WorkflowForm operation="create-form" fields={{org:id}} label={c("إنشاء مسودة","Create draft")} locale={locale}><label>{c("اسم النموذج","Form name")}<input name="title" dir="auto" required minLength={2} maxLength={120}/></label><label>{c("نسخ من نموذج","Copy from form")}<select name="source"><option value="">{c("نموذج من الصفر","Start from scratch")}</option>{workspace.templates.map(t=><option key={t.id} value={t.id}>{t.name}{!t.organization_id?c(" · نموذج LUB"," · LUB template"):""}</option>)}</select></label></WorkflowForm>
 <ul className="mt-6 space-y-3">{own.map(t=><li key={t.id}><Link dir="auto" href={`?template=${t.id}`} className="text-link">{t.name}</Link> · {t.versions.filter(v=>v.status_code==="Published").length} {c("نسخ منشورة","published versions")}</li>)}</ul>
 {selected&&version&&<div className="mt-8 space-y-6 border-t border-line pt-6"><h3 className="text-lg font-semibold"><bdi>{selected.name}</bdi> · {c("النسخة","version")} {version.version_number} · {en?version.status_code:statuses[version.status_code]}</h3>{version.status_code==="Draft"?<><FormEditor key={version.id} version={version.id} revision={version.revision} initial={version.definition} locale={locale}/><WorkflowForm operation="publish-form" fields={{version:version.id}} label={c("نشر النسخة المحفوظة","Publish saved version")} locale={locale}><p className="text-sm text-muted">{c("احفظ تعديلاتك أولًا. النشر يثبّت النسخة المحفوظة ولا يغيّر طلبات الطلاب السابقة.","Save your edits first. Publishing locks the saved version and does not change earlier student applications.")}</p></WorkflowForm></>:<><ul className="space-y-2">{version.definition.sections.flatMap(s=>s.fields).map(f=><li key={f.id} dir="auto">{f.label}{f.required?" *":""}</li>)}</ul><WorkflowForm operation="draft-form" fields={{template:selected.id}} label={c("بدء مسودة نسخة جديدة","Start a new draft version")} locale={locale}/></>}</div>}</section>}
 {allowed("REGISTRATION_ROUNDS_MANAGE")&&<section className="panel mb-6 p-6"><h2 className="mb-5 text-xl font-semibold">{c("جولات التسجيل","Registration rounds")}</h2><WorkflowForm operation="create-round" fields={{org:id}} label={c("إنشاء جولة مسودة","Create draft round")} locale={locale}><label>{c("عنوان الجولة","Round title")}<input name="title" dir="auto" required minLength={2} maxLength={120}/></label><label>{c("النموذج المنشور","Published form")}<select name="template" required><option value="">{c("اختر نموذجًا","Select a form")}</option>{own.filter(t=>t.versions.some(v=>v.status_code==="Published")).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><DateInput name="opens" label={c("بداية التسجيل","Registration opens")} required locale={locale}/><DateInput name="closes" label={c("نهاية التسجيل","Registration closes")} required locale={locale}/></div><label className="flex items-center gap-3"><input type="checkbox" name="withdrawal" defaultChecked className="size-5"/>{c("السماح بسحب الطلب قبل القرار النهائي","Allow withdrawal before the final decision")}</label></WorkflowForm>
 <ul className="mt-6 space-y-6">{workspace.rounds.map(r=><li key={r.id} className="border-t border-line pt-5"><h3 className="font-semibold"><bdi>{r.title}</bdi> · {en?r.status_code:statuses[r.status_code]}</h3><p className="my-3 text-sm leading-7 text-muted">{c("من","From")} {new Date(r.opens_at).toLocaleString(en?"en-US":"ar-SA",{timeZone:"Asia/Riyadh",calendar:"gregory"})} {c("إلى","to")} {new Date(r.closes_at).toLocaleString(en?"en-US":"ar-SA",{timeZone:"Asia/Riyadh",calendar:"gregory"})}{r.status_code==="Open"&&!r.open?c(" · خارج فترة التقديم"," · Outside application period"):""}</p><div className="flex flex-wrap gap-3">{(r.status_code==="Draft"?["Open","Archived"]:r.status_code==="Open"?["Closed"]:r.status_code==="Closed"?["Archived"]:[]).map(status=><WorkflowForm key={status} operation="round-status" fields={{round:r.id,status}} label={en?status==="Open"?"Open round":status==="Closed"?"Close round":"Archive round":status==="Open"?"فتح الجولة":status==="Closed"?"إغلاق الجولة":"أرشفة الجولة"} locale={locale}/>)}</div></li>)}</ul></section>}
 <section className="panel mb-6 p-6"><h2 className="mb-5 text-xl font-semibold">{c("طلبات الانضمام","Applications")}</h2><form action={searchApplications} className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="org" value={id}/><label>{c("اسم الطالب","Student name")}<input name="q" dir="auto" maxLength={120} defaultValue={filters.q}/></label><label>{c("الحالة","Status")}<select name="status" defaultValue={filters.status}><option value="">{c("الكل","All")}</option>{["Submitted","Interview","Accepted","Rejected","Withdrawn"].map(s=><option key={s} value={s}>{en?s:statuses[s]}</option>)}</select></label><label>{c("اللجنة","Committee")}<select name="committee" defaultValue={filters.committee}><option value="">{c("الكل","All")}</option>{workspace.committees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{c("التخصص","Major")}<input name="major" dir="auto" maxLength={120} defaultValue={filters.major}/></label><label>{c("المستوى","Level")}<input name="level" maxLength={20} defaultValue={filters.level}/></label><label>{c("من تاريخ","From date")}<input type="date" name="from" defaultValue={filters.from}/></label><label>{c("إلى تاريخ","To date")}<input type="date" name="to" defaultValue={filters.to}/></label><label>{c("مشاركة سابقة","Prior participation")}<select name="activity" defaultValue={filters.activity}><option value="">{c("الكل","All")}</option><option value="prior">{c("له عضوية سابقة","Previously a member")}</option><option value="first">{c("أول عضوية","First membership")}</option></select></label><label>{c("الرقم الجامعي (بحث خاص لمدة 10 دقائق)","University number (private search for 10 minutes)")}<input name="university" inputMode="numeric" maxLength={15} autoComplete="off"/></label><button className="button">{c("تصفية","Filter")}</button></form>
 <WorkflowForm disabled={!rows.some(a=>a.canBulk)} operation="bulk" label={c("تنفيذ على الطلبات المحددة","Apply to selected applications")} locale={locale}>
 <ApplicationSelection rows={rows.slice(0,25)} org={id} locale={locale}/>{rows.length===0&&<p className="text-muted">{c("لا توجد طلبات مطابقة ضمن صلاحياتك.","No matching applications within your permissions.")}</p>}
 <label>{c("القرار الجماعي","Bulk decision")}<select name="status"><option value="Accepted">{c("قبول","Accept")}</option><option value="Rejected">{c("رفض","Reject")}</option><option value="Interview">{c("مقابلة","Interview")}</option></select></label><label>{c("رسالة المقابلة","Interview message")}<textarea name="message" dir="auto" maxLength={3000}/></label><p className="text-sm leading-7 text-muted">{c("يطبّق الإجراء على المحدد فقط، ويظهر زر التراجع بعد العملية مع حفظ السجل. عند اختيار مقابلة، الرسالة مطلوبة وتظهر للطلاب.","The action applies only to selected applications. An undo button appears afterward while preserving the record. An interview requires a message visible to students.")}</p>
 </WorkflowForm><nav className="mt-5 flex gap-4" aria-label={c("صفحات الطلبات","Application pages")}>{filters.page>1&&<Link className="text-link" href={pageHref(filters.page-1)}>{c("السابق","Previous")}</Link>}{rows.length>25&&<Link className="text-link" href={pageHref(filters.page+1)}>{c("التالي","Next")}</Link>}</nav></section>
 {allowed("PERMISSIONS_GRANT")&&<section className="panel p-6"><h2 className="mb-5 text-xl font-semibold">{c("تفويض صلاحيات التشغيل","Delegate operational permissions")}</h2><WorkflowForm operation="grant" label={c("منح الصلاحية","Grant permission")} locale={locale}><label>{c("العضو","Member")}<select name="member" required><option value="">{c("اختر عضوًا نشطًا","Select an active member")}</option>{workspace.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>{c("الصلاحية","Permission")}<select name="capability">{Object.entries(capabilities).filter(([code])=>code!=="PERMISSIONS_GRANT").map(([code,label])=><option key={code} value={code}>{en?code.replaceAll("_"," "):label}</option>)}</select></label><label>{c("نطاق اللجنة","Committee scope")}<select name="committee"><option value="">{c("الجهة بالكامل","Entire organization")}</option>{workspace.committees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><DateInput name="ends" label={c("انتهاء التفويض (اختياري)","Permission ends (optional)")} locale={locale}/><p className="text-sm text-muted">{c("نطاق اللجنة متاح لصلاحيات الطلبات فقط.","Committee scope is available only for application permissions.")}</p></WorkflowForm><ul className="mt-6 space-y-4">{workspace.members.flatMap(m=>m.grants.map(g=><li key={g.id} className="border-t border-line pt-4"><p className="mb-3"><bdi>{m.name}</bdi> · {en?g.code.replaceAll("_"," "):capabilities[g.code]} · <bdi>{g.committee??c("الجهة بالكامل","Entire organization")}</bdi></p><WorkflowForm operation="end-grant" fields={{grant:g.id}} label={c("إنهاء التفويض","End permission")} locale={locale}/></li>))}</ul></section>}
 </>;
}
