import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import { redirect } from "next/navigation";
import { requireUser } from "@/features/auth/session";
import { getMyPageData } from "@/features/organizations/my-page-repository";
import { AccountHeader } from "@/components/account-header";
import { StorageUnavailable } from "@/components/storage-unavailable";
import { isProfileStorageConfigured } from "@/lib/env";
import {taskLabels} from "@/features/tasks/repository";
import {taskLabelsEn} from "@/features/tasks/display";
import {getPreferences} from "@/lib/preferences";

export async function generateMetadata(){return localizedMetadata('صفحتي','My page');}
export default async function MyPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const en=(await getPreferences()).locale==="en";
  const user = await requireUser();
  if (!isProfileStorageConfigured()) return <><AccountHeader /><StorageUnavailable /></>;
  const {status,profile,access,memberships,tasks,hours}=await getMyPageData(user.id);
  if (status === "Inactive") redirect("/account-unavailable");
  if (!profile) redirect("/onboarding");
  const roleLabels: Record<string, string> = en?{ OL: "Organization leader", OD: "Deputy leader", CL: "Committee leader", CD: "Deputy committee leader" }:{ OL: "قائد الجهة", OD: "نائب القائد", CL: "قائد اللجنة", CD: "نائب قائد اللجنة" };
  const formatDate = (value: string) => new Intl.DateTimeFormat(en?"en-US":"ar-SA", { dateStyle: "medium", calendar: "gregory", timeZone: "Asia/Riyadh" }).format(new Date(value));
  const { notice } = await searchParams;
  return <><AccountHeader /><main id="main" className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14">
    {notice === "profile-saved" && <p role="status" className="notice-success mb-6 rounded-lg border border-green-200 bg-green-50 p-4 text-action">{en?"Your details were saved.":"تم حفظ بياناتك."}</p>}
    {notice === "signout-failed" && <p role="alert" className="error-message mb-6">{en?"Could not sign out. Please try again.":"تعذّر تسجيل الخروج. حاول مرة ثانية."}</p>}
    <div className="mb-10 flex flex-wrap items-center justify-between gap-5"><div><h1 className="text-3xl font-bold">{en?"Hello, ":"أهلًا، "}<bdi>{profile.fullName}</bdi></h1><p className="mt-3 text-muted">{en?"Your memberships and activities come together here.":"هنا تجتمع عضوياتك ومشاركاتك."}</p></div><div className="flex flex-wrap gap-3">{(access.superAdmin || access.organizations.length > 0) && <Link href="/manage" className="button">{en?access.superAdmin?"System management":"Manage organizations and committees":access.superAdmin ? "إدارة النظام" : "إدارة الجهات واللجان"}</Link>}<Link href="/applications" className="button button-secondary">{en?"Applications":"طلبات الانضمام"}</Link><Link href="/account" className="button button-secondary">{en?"My details and privacy":"بياناتي والخصوصية"}</Link></div></div>
    <section aria-labelledby="basic-title" className="panel p-6"><h2 id="basic-title" className="text-lg font-semibold">{en?"Basic details":"بياناتي الأساسية"}</h2><dl className="mt-5 grid gap-5 sm:grid-cols-3"><div><dt className="text-sm text-muted">{en?"Major":"التخصص"}</dt><dd dir="auto" className="mt-2 font-medium">{profile.major}</dd></div><div><dt className="text-sm text-muted">{en?"Academic level":"المستوى الدراسي"}</dt><dd className="mt-2 font-medium">{en?profile.academicLevel==="graduate"?"Graduate studies":`Level ${profile.academicLevel}`:profile.academicLevel === "graduate" ? "دراسات عليا" : `المستوى ${profile.academicLevel}`}</dd></div><div><dt className="text-sm text-muted">{en?"Public profile":"الملف العام"}</dt><dd className="mt-2 font-medium">{en?profile.publicProfileEnabled?"Visible when available":"Private":profile.publicProfileEnabled ? "الظهور مسموح عند إتاحته" : "خاص"}</dd></div></dl></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2">
      <section className="panel p-6"><h2 className="text-lg font-semibold">{en?"Memberships and role history":"عضوياتي وسجل أدواري"}</h2>{memberships.length ? <ul className="mt-5 divide-y divide-line">{memberships.map(membership => <li key={membership.id} className="py-5 first:pt-0 last:pb-0"><Link href={`/organizations/${membership.slug}`} dir="auto" className="text-link">{membership.organizationName}</Link><p className="mt-2 text-sm leading-7 text-muted">{en?membership.statusCode==="Active"?"Active membership":membership.statusCode==="Inactive"?"Inactive membership":"Ended membership":membership.statusCode === "Active" ? "عضوية نشطة" : membership.statusCode === "Inactive" ? "عضوية غير نشطة" : "عضوية منتهية"}{membership.organizationStatus === "Archived" && (en?" · Organization archived":" · الجهة مؤرشفة")}<br />{en?"From ":"من "}{formatDate(membership.startDate)}{membership.endDate && <> {en?"to":"إلى"} {formatDate(membership.endDate)}</>}</p>{membership.roles.length > 0 && <ul className="mt-3 space-y-2 text-sm leading-7">{membership.roles.map((role, index) => <li key={index}>{roleLabels[role.code]} · {en?"from":"من"} {formatDate(role.startDate)}{role.endDate ? <> {en?"to":"إلى"} {formatDate(role.endDate)}</> : en?", ongoing":"، مستمر"}</li>)}</ul>}</li>)}</ul> : <><p className="mt-5 font-medium">{en?"Your memberships have not started yet.":"لم تبدأ عضوياتك بعد."}</p><p className="mt-2 text-sm leading-7 text-muted">{en?"Find organizations that match your interests.":"تعرّف على الجهات التي تناسب اهتمامك."}</p><Link href="/organizations" className="text-link mt-4 inline-block">{en?"Explore clubs and councils":"استكشف الأندية والمجالس"}</Link></>}</section>
      <section className="panel p-6"><h2 className="text-lg font-semibold">{en?"Current tasks":"مهامي الحالية"}</h2>{tasks.length?<ul className="mt-5 space-y-4">{tasks.map(t=><li key={t.id}><Link dir="auto" className="text-link" href={`/tasks/${t.id}`}>{t.title}</Link><p className="mt-2 text-sm text-muted">{en?taskLabelsEn[t.status]:taskLabels[t.status]}</p></li>)}</ul>:<p className="mt-5 leading-8 text-muted">{en?"No current task participation to show.":"لا توجد مشاركات حالية لعرضها الآن."}</p>}<Link className="text-link mt-5 inline-block" href="/tasks">{en?"Available tasks and participation history":"المهام المتاحة وسجل مشاركاتي"}</Link><Link className="text-link mt-5 ms-5 inline-block" href="/notifications">{en?"Notifications":"الإشعارات"}</Link></section>
      <section className="panel p-6"><h2 className="text-lg font-semibold">{en?"Hours and renewals":"الساعات والتجديد"}</h2><p className="mt-5 text-xl font-semibold">{en?`${hours} approved hours`:`${hours} ساعة معتمدة`}</p><div className="mt-5 flex flex-wrap gap-5"><Link className="text-link" href="/account/talent">{en?"Skills profile and privacy":"ملفي المهاري والخصوصية"}</Link><Link className="text-link" href="/hours">{en?"Hours history":"سجل ساعاتي"}</Link><Link className="text-link" href="/renewals">{en?"Membership renewals":"تجديد عضوياتي"}</Link><Link className="text-link" href="/documents">{en?"My documents":"مستنداتي"}</Link></div></section>
      <section className="panel p-6"><h2 className="text-lg font-semibold">{en?"My events":"فعالياتي"}</h2><p className="mt-4 leading-8 text-muted">{en?"Your registrations and attendance are saved in your event history.":"تسجيلاتي وحضوري محفوظة في سجل الفعاليات."}</p><Link href="/events/mine" className="text-link mt-4 inline-block">{en?"View my events":"عرض فعالياتي"}</Link></section>
    </div>
  </main></>;
}
