"use client";
import {useState} from "react";
import {WorkflowForm} from "@/features/forms/mutation-form";
import {mutateTalent} from "./actions";
import type {Locale} from "@/lib/preferences";
export function TalentForm(props:Omit<Parameters<typeof WorkflowForm>[0],"mutation">){return <WorkflowForm {...props} mutation={mutateTalent}/>;}
export function Visibility({name,label,value=false}:{name:string;label:string;value?:boolean}){return <label className="flex items-center gap-3"><input type="checkbox" name={name} defaultChecked={value} className="size-5 shrink-0"/>{label}</label>;}
export function LinkFields({value,locale="ar"}:{value?:{link_type:string;label:string;url_or_value:string;is_public:boolean};locale?:Locale}){const en=locale==="en";return <><label>{en?"Contact type":"نوع التواصل"}<select name="kind" defaultValue={value?.link_type??"Website"}>{Object.entries(en?{Email:"Email",Phone:"Phone",Website:"Website",LinkedIn:"LinkedIn",GitHub:"GitHub"}:{Email:"البريد",Phone:"الهاتف",Website:"الموقع",LinkedIn:"LinkedIn",GitHub:"GitHub"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>{en?"Contact label":"عنوان قناة التواصل"}<input name="label" required maxLength={80} defaultValue={value?.label}/></label><label>{en?"URL, email or phone":"الرابط أو البريد أو الهاتف"}<input name="value" dir="ltr" required maxLength={2048} defaultValue={value?.url_or_value}/></label><Visibility name="visible" label={en?"Show this contact publicly":"إظهار قناة التواصل للعامة"} value={value?.is_public}/></>;}
export function ProjectFields({value,locale="ar"}:{value?:{display_title:string;display_description:string;is_public:boolean;is_featured:boolean};locale?:Locale}){const en=locale==="en";return <><label>{en?"Public achievement title":"عنوان الإنجاز العام"}<input name="title" required minLength={2} maxLength={120} defaultValue={value?.display_title}/></label><label>{en?"Achievement summary":"ملخص الإنجاز"}<textarea name="description" maxLength={1000} rows={3} defaultValue={value?.display_description}/></label><Visibility name="visible" label={en?"Show this achievement publicly":"إظهار هذا الإنجاز للعامة"} value={value?.is_public}/><Visibility name="featured" label={en?"Pin achievement to the top":"تثبيت الإنجاز في الأعلى"} value={value?.is_featured}/><p className="text-sm leading-7 text-muted">{en?"Write a summary suitable for publication. Task files and internal descriptions remain private.":"اكتب ملخصًا يصلح للنشر. ملفات المهمة ووصفها الداخلي لا تظهر للعامة."}</p></>;}
export function NewProject({sources,locale="ar"}:{sources:Array<{id:string;kind:string;title:string}>;locale?:Locale}){const [selected,setSelected]=useState(sources[0]?.id??"");const source=sources.find(s=>s.id===selected),en=locale==="en";return <TalentForm operation="project" fields={{...(source?.kind==="Task"?{participant:selected}:{contribution:selected})}} label={en?"Add achievement":"إضافة الإنجاز"} locale={locale}><label>{en?"Verified activity":"النشاط الموثق"}<select required value={selected} onChange={e=>setSelected(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id} dir="auto">{s.kind==="Task"?en?"Task":"مهمة":en?"Contribution":"مساهمة"} · {s.title}</option>)}</select></label><ProjectFields locale={locale}/></TalentForm>;}
