import Link from "next/link";
import type {PublicTalent,TalentCard,TalentPages} from "./repository";
import {eventDate,eventDateEn,eventLabels,eventLabelsEn} from "@/features/events/display";
import type {Locale} from "@/lib/preferences";
const roleLabels:Record<string,string>={OL:"قائد الجهة",OD:"نائب القائد",CL:"قائد اللجنة",CD:"نائب قائد اللجنة"};
const roleLabelsEn:Record<string,string>={OL:"Organization leader",OD:"Deputy leader",CL:"Committee leader",CD:"Deputy committee leader"};
export function TalentPagination({pages,keyName,more,locale="ar"}:{pages:TalentPages;keyName:keyof TalentPages;more:boolean;locale?:Locale}){const en=locale==="en";const href=(p:number)=>`?${new URLSearchParams({...Object.fromEntries(Object.entries(pages).map(([k,v])=>[k,String(v)])),[keyName]:String(p)})}`;return <nav className="mt-5 flex gap-5" aria-label={en?`${keyName} pages`:`صفحات ${keyName}`}>{pages[keyName]>0&&<Link className="text-link" href={href(pages[keyName]-1)}>{en?"Previous":"السابق"}</Link>}{more&&<Link className="text-link" href={href(pages[keyName]+1)}>{en?"Next":"التالي"}</Link>}</nav>;}
export function TalentCards({items,locale="ar"}:{items:TalentCard[];locale?:Locale}){const en=locale==="en";return items.length?<ul className="grid gap-5 sm:grid-cols-2">{items.map(t=><li key={t.id} className="panel min-w-0 p-6"><h2 dir="auto" className="text-xl font-semibold"><Link href={`/talent/${t.id}`} className="text-link">{t.name}</Link></h2><p dir="auto" className="mt-3 text-muted">{t.major}</p>{t.bio&&<p dir="auto" className="mt-3 line-clamp-3 leading-8 wrap-anywhere">{t.bio}</p>}<ul className="mt-4 flex flex-wrap gap-2" aria-label={en?"Published skills":"مهارات يصرّح بها الطالب"}>{t.skills.map(s=><li key={s} dir="auto" className="rounded-full bg-mist px-3 py-1 text-sm wrap-anywhere">{s}</li>)}</ul></li>)}</ul>:<p className="panel p-8 text-muted">{en?"No matching published talent profiles right now.":"لا توجد ملفات مهارية منشورة مطابقة الآن."}</p>;}
export function PublicTalentView({profile:p,pages,locale="ar"}:{profile:PublicTalent;pages:TalentPages;locale?:Locale}){const en=locale==="en",labels=en?eventLabelsEn:eventLabels,date=en?eventDateEn:eventDate,roles=en?roleLabelsEn:roleLabels;return <>
 <section className="panel mb-6 p-6 sm:p-8"><p className="text-sm text-muted">{en?"Skills profile":"الملف المهاري"}</p><h1 dir="auto" className="mt-3 text-3xl font-bold leading-normal">{p.name}</h1><p className="mt-3 text-muted"><bdi>{p.major}</bdi> · {en?"Level":"المستوى"} {en?p.level==="graduate"?"Graduate":p.level:p.level==="graduate"?"خريج":p.level}</p>{p.bio&&<p dir="auto" className="mt-5 whitespace-pre-wrap leading-8 wrap-anywhere">{p.bio}</p>}{p.total!==null&&<p className="mt-6 text-2xl font-semibold text-action">{en?`${p.total} visible approved hours`:`${p.total} ساعة معتمدة ظاهرة`}</p>}<ul className="mt-5 flex flex-wrap gap-2" aria-label={en?"Published skills":"مهارات يصرّح بها الطالب"}>{p.skills.map(s=><li key={s} dir="auto" className="rounded-full bg-mist px-3 py-1 wrap-anywhere">{s}</li>)}</ul>{p.links.length>0&&<nav className="mt-6 flex flex-wrap gap-5" aria-label={en?"Published contact channels":"قنوات التواصل المنشورة"}>{p.links.map((l,i)=><a className="text-link wrap-anywhere" key={i} href={l.kind==="Email"?`mailto:${l.value}`:l.kind==="Phone"?`tel:${l.value}`:l.value} rel="noopener noreferrer">{l.label}</a>)}</nav>}</section>
 {p.organizations.length>0&&<section className="panel mb-6 p-6"><h2 className="mb-5 text-xl font-semibold">{en?"Organizations, roles, and hours":"الجهات والأدوار والساعات"}</h2><ul className="space-y-5">{p.organizations.slice(0,25).map(o=><li className="border-t border-line pt-4" key={o.id}><Link dir="auto" href={`/organizations/${o.slug}`} className="text-link font-medium">{o.name}</Link>{o.archived&&<span className="ms-3 text-sm text-muted">{en?"Archived organization":"جهة مؤرشفة"}</span>}{o.hours!==null&&<p className="mt-3">{en?`${o.hours} approved hours`:`${o.hours} ساعة معتمدة`}</p>}<ul className="mt-3 space-y-3">{o.memberships.map((m,i)=><li key={i} className="text-sm leading-7 text-muted">{en?"Member from":"عضوية من"} {m.start_date}{m.end_date?en?` to ${m.end_date}`:` إلى ${m.end_date}`:en?", ongoing":"، مستمرة"}{m.roles.map((r,j)=><p key={j}>{roles[r.code]} · {r.starts}{r.ends?` — ${r.ends}`:""}</p>)}</li>)}</ul></li>)}</ul><TalentPagination pages={pages} keyName="organizations" more={p.organizations.length>25} locale={locale}/></section>}
 {p.events.length>0&&<section className="panel mb-6 p-6"><h2 className="mb-5 text-xl font-semibold">{en?"Attendance and contributions":"الحضور والمساهمات"}</h2><ul className="space-y-5">{p.events.slice(0,25).map(e=><li key={e.id}><Link dir="auto" className="text-link font-medium" href={`/events/${e.id}`}>{e.title}</Link><p className="mt-2 text-sm text-muted"><bdi>{e.organization}</bdi>{e.archived?en?" · Archived organization":" · جهة مؤرشفة":""} · {date(e.starts_at)}</p>{e.contributions.map((c,i)=><p key={i} className="mt-3 rounded-lg bg-mist p-3 font-medium">{labels[c.kind]} · <bdi>{c.title}</bdi></p>)}</li>)}</ul><TalentPagination pages={pages} keyName="events" more={p.events.length>25} locale={locale}/></section>}
 {p.projects.length>0&&<section className="panel p-6"><h2 className="mb-5 text-xl font-semibold">{en?"Achievements and projects":"الإنجازات والمشاريع"}</h2><ul className="space-y-5">{p.projects.slice(0,25).map(a=><li className="border-t border-line pt-4" key={a.id}><h3 dir="auto" className="font-semibold">{a.title}{a.featured&&<span className="ms-3 text-sm text-action">{en?"Featured":"مثبت"}</span>}</h3><p dir="auto" className="mt-3 whitespace-pre-wrap leading-8 wrap-anywhere">{a.description}</p></li>)}</ul><TalentPagination pages={pages} keyName="projects" more={p.projects.length>25} locale={locale}/></section>}
 </>;}
