import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import { requireUser } from "@/features/auth/session";
import { redirect } from "next/navigation";
import { getManagementDashboard } from "@/features/organizations/management-repository";
import { MutationForm } from "@/features/organizations/mutation-form";
import { OrganizationTextFields } from "@/features/organizations/form-fields";
import { organizationTypes, organizationStatuses } from "@/features/organizations/validation";
import { getPreferences } from "@/lib/preferences";

export async function generateMetadata(){return localizedMetadata('إدارتي','Management');}
export default async function ManagePage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const en=(await getPreferences()).locale==="en";
  const user = await requireUser();
  let dashboard: Awaited<ReturnType<typeof getManagementDashboard>>;
  try {
    dashboard = await getManagementDashboard(user.id);
  } catch { throw new Error("Management storage is unavailable."); }
  if (dashboard.readiness.status === "Inactive") redirect("/account-unavailable");
  if (!dashboard.readiness.onboarded) redirect("/onboarding");
  const { access, roster, admins } = dashboard;
  const { notice } = await searchParams;
  return <>
    <h1 className="text-3xl font-bold">{en?access.superAdmin?"System management":"Management":access.superAdmin ? "إدارة النظام" : "إدارتي"}</h1>
    {access.superAdmin&&<Link className="text-link mt-5 inline-block" href="/manage/terms">{en?"Academic terms":"تعريف الفصول الأكاديمية"}</Link>}
    <p className="mt-3 mb-8 leading-8 text-muted">{en?access.superAdmin?"Create organizations, appoint leaders, and manage system administrators.":"Organizations and committees you can manage.":access.superAdmin ? "أنشئ الجهات، وعيّن قيادتها، وأدر المشرفين العامين." : "الجهات واللجان التي تملك صلاحية إدارتها."}</p>
    {notice === "organization-created" && <p role="status" className="panel mb-6 p-4 text-action">{en?"Organization created. You can now appoint its primary leader.":"تم إنشاء الجهة. يمكنك الآن تعيين قائدها الأساسي."}</p>}
    {(access.organizations.length > 0 || !access.superAdmin) && <section aria-labelledby="managed-title" className="mb-8"><h2 id="managed-title" className="mb-4 text-xl font-semibold">{en?"Organizations I manage":"الجهات التي أديرها"}</h2>{access.organizations.length ? <ul className="grid gap-4 md:grid-cols-2">{access.organizations.map(organization => <li key={organization.id} className="panel p-6"><h3 dir="auto" className="text-lg font-semibold">{organization.nameAr}</h3><p className="mt-2 text-sm text-muted">{en?organization.canEdit||organization.canManageCommittees?"Organization management":"Committee management within your permissions":organization.canEdit || organization.canManageCommittees ? "إدارة الجهة" : "إدارة اللجنة ضمن صلاحياتك"}</p><Link href={`/manage/organizations/${organization.id}`} className="button button-secondary mt-5">{en?"Open management":"فتح الإدارة"}</Link></li>)}</ul> : <div className="panel p-6"><p className="font-medium">{en?"You do not manage any organizations yet.":"لا توجد جهات تملك صلاحية إدارتها الآن."}</p><p className="mt-2 leading-8 text-muted">{en?"Organizations appear here when you are assigned an administrative role or given an appropriate permission.":"تظهر هنا الجهات عند تعيينك في دور إداري أو منحك صلاحية مناسبة."}</p><Link href="/organizations" className="text-link mt-4 inline-block">{en?"Explore clubs and councils":"استكشف الأندية والمجالس"}</Link></div>}</section>}
    {access.superAdmin && <div className="space-y-8">
      <section id="organizations" aria-labelledby="org-list-title" className="panel p-6 sm:p-8"><h2 id="org-list-title" className="text-xl font-semibold">{en?"Organizations and leader appointments":"المنظمات وتعيين القادة"}</h2>{roster.length ? <ul className="mt-6 divide-y divide-line">{roster.map(organization => <li key={organization.id} className="py-5 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 dir="auto" className="text-lg font-semibold">{organization.nameAr}</h3><p className="mt-2 text-sm text-muted">{en?organization.typeCode:organizationTypes[organization.typeCode as keyof typeof organizationTypes]} · {en?organization.statusCode:organizationStatuses[organization.statusCode as keyof typeof organizationStatuses]}</p></div><Link href={`/organizations/${organization.slug}`} className="text-link text-sm">{en?"Public page":"الصفحة العامة"}</Link></div>
        {organization.statusCode === "Active" && <details className="mt-5 rounded-lg border border-line p-4"><summary className="cursor-pointer font-medium">{en?"Appoint or replace the primary leader":"تعيين أو استبدال القائد الأساسي"}</summary><div className="mt-5"><p className="mb-4 text-sm leading-7 text-muted">{en?"The account must be verified and onboarded. Replacing a leader ends the previous role while preserving its history and their membership.":"يجب أن يكون الحساب متحققًا ومكتمل البيانات. الاستبدال ينهي الدور السابق ويحفظ تاريخه، ولا ينهي عضوية القائد السابق."}</p><MutationForm operation="appoint-leader" fields={{ organizationId: organization.id }} submitLabel={en?"Appoint leader":"تعيين القائد"} confirmLabel={en?"I confirm appointing this account as primary leader":"أؤكد تعيين هذا الحساب قائدًا أساسيًا"} locale={en?"en":"ar"}><div><label htmlFor={`leader-${organization.id}`}>{en?"Leader email":"بريد القائد"}</label><input id={`leader-${organization.id}`} name="email" type="email" dir="ltr" required maxLength={254} autoComplete="off" /></div></MutationForm></div></details>}
        <details className="mt-3 rounded-lg border border-line p-4"><summary className="cursor-pointer font-medium">{en?"Change organization status":"تغيير حالة الجهة"}</summary><div className="mt-5"><p className="mb-4 text-sm leading-7 text-muted">{en?"Archiving stops operations while preserving the public page and historical records.":"الأرشفة توقف العمليات وتحتفظ بالصفحة العامة والسجلات التاريخية."}</p><MutationForm operation="org-status" fields={{ organizationId: organization.id }} submitLabel={en?"Update status":"تحديث الحالة"} confirmLabel={en?"I confirm changing this organization's status":"أؤكد تغيير حالة الجهة"} locale={en?"en":"ar"}><div><label htmlFor={`status-${organization.id}`}>{en?"Status":"الحالة"}</label><select id={`status-${organization.id}`} name="status" defaultValue={organization.statusCode}>{Object.entries(organizationStatuses).map(([code, label]) => <option key={code} value={code}>{en?code:label}</option>)}</select></div></MutationForm></div></details>
      </li>)}</ul> : <p className="mt-5 text-muted">{en?"No organizations have been added yet. Create the first one below.":"لم تُضف أي جهة بعد. ابدأ بإنشاء أول جهة أدناه."}</p>}</section>
      <section aria-labelledby="create-title" className="panel p-6 sm:p-8"><h2 id="create-title" className="mb-6 text-xl font-semibold">{en?"Add organization":"إضافة جهة"}</h2><MutationForm operation="create-org" submitLabel={en?"Create organization":"إنشاء الجهة"} locale={en?"en":"ar"}><OrganizationTextFields prefix="create" locale={en?"en":"ar"}/><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="create-type">{en?"Organization type":"نوع الجهة"}</label><select id="create-type" name="typeCode"><option value="Club">{en?"Club":"نادي"}</option><option value="Council">{en?"Council":"مجلس"}</option></select></div><div><label htmlFor="create-slug">{en?"URL name":"اسم الرابط"}</label><input id="create-slug" name="slug" dir="ltr" required maxLength={80} pattern="[a-z0-9]+(-[a-z0-9]+)*" aria-describedby="slug-help" /><p id="slug-help" className="mt-2 text-sm leading-7 text-muted">{en?"Lowercase English letters and digits, such as tech-club. The URL stays fixed to preserve the organization's history.":"حروف إنجليزية صغيرة وأرقام، مثل tech-club. يبقى الرابط ثابتًا لحفظ تاريخ الجهة."}</p></div></div></MutationForm></section>
      <section id="admins" aria-labelledby="admins-title" className="panel p-6 sm:p-8"><h2 id="admins-title" className="text-xl font-semibold">{en?"System administrators":"المشرفون العامون"}</h2><p className="mt-3 text-sm leading-7 text-muted">{en?"The last active system administrator cannot be removed. System access does not automatically grant daily organization management.":"لا يمكن إنهاء صلاحية آخر مشرف عام نشط. صلاحية النظام لا تمنح إدارة يومية للجهات تلقائيًا."}</p><ul className="mt-6 divide-y divide-line">{admins.map(admin => <li key={admin.userId} className="py-5 first:pt-0"><p className="font-medium"><bdi>{admin.fullName}</bdi>{admin.userId === user.id && (en?" (you)":" (أنت)")}</p>{admins.length > 1 && <details className="mt-3"><summary className="cursor-pointer text-sm text-muted">{en?"End permission":"إنهاء الصلاحية"}</summary><div className="mt-4"><MutationForm operation="end-admin" fields={{ targetUserId: admin.userId }} submitLabel={en?"End administrator permission":"إنهاء صلاحية المشرف"} confirmLabel={en?"I confirm ending this administrator's permission":"أؤكد إنهاء صلاحية هذا المشرف العام"} locale={en?"en":"ar"}/></div></details>}</li>)}</ul><div className="mt-6 border-t border-line pt-6"><h3 className="mb-5 text-lg font-semibold">{en?"Add system administrator":"إضافة مشرف عام"}</h3><MutationForm operation="grant-admin" submitLabel={en?"Grant system administrator access":"منح صلاحية المشرف العام"} confirmLabel={en?"I confirm granting this account system management access":"أؤكد منح هذا الحساب صلاحية إدارة النظام"} locale={en?"en":"ar"}><div><label htmlFor="admin-email">{en?"Verified, onboarded account email":"بريد الحساب المتحقق والمكتمل"}</label><input id="admin-email" name="email" type="email" dir="ltr" required maxLength={254} autoComplete="off" /></div></MutationForm></div></section>
    </div>}
  </>;
}
