import Link from "next/link";
import {HoursForm} from "@/features/hours/form";
import {hourLabels,hourLabelsEn,TermSelect} from "@/features/hours/view";
import {DateInput} from "@/features/forms/date-input";
import {formatTaskDate,formatTaskDateEn} from "@/features/tasks/display";
import {TaskPagination} from "@/features/tasks/task-list";
import type {Campaign,PersonalRenewals,RenewalWorkspace} from "./repository";
import type {Locale} from "@/lib/preferences";
const campaignLabel=(campaign:Campaign,locale:Locale)=>campaign.status_code==="Open"&&new Date(campaign.closes_at)<=new Date()?locale==="en"?"Response period ended":"انتهت فترة الردود":(locale==="en"?hourLabelsEn:hourLabels)[campaign.status_code];
export function PersonalRenewalsView({data,page,locale="ar"}:{data:PersonalRenewals;page:number;locale?:Locale}){const en=locale==="en",c=(ar:string,english:string)=>en?english:ar,labels=en?hourLabelsEn:hourLabels,date=en?formatTaskDateEn:formatTaskDate;return <div className="space-y-8"><div><h1 className="text-3xl font-bold">{c("تجديد عضوياتي","My membership renewals")}</h1><p className="mt-3 leading-8 text-muted">{c("التجديد يوثّق ردك للفصل، ويحفظ عضويتك وساعاتك وتاريخك.","Renewal records your response for the term while preserving your membership, hours and history.")}</p></div>{data.items.length?<ul className="space-y-5">{data.items.slice(0,25).map(({campaign,response:r})=><li key={r.id} className="panel min-w-0 space-y-4 p-6"><h2 dir="auto" className="text-xl font-semibold break-words">{campaign.org_name} · {campaign.name}</h2><p className="text-sm leading-7 text-muted">{campaignLabel(campaign,locale)} · {c("من","from")} {date(campaign.opens_at)} {c("إلى","to")} {date(campaign.closes_at)}</p><p>{r.response_code==="Pending"?c("بانتظار ردك","Awaiting your response"):labels[r.response_code]}</p>{r.canRespond&&<HoursForm operation="respond" fields={{response:r.id}} label={c("حفظ رد التجديد","Save renewal response")} locale={locale}><label>{c("ردك","Your response")}<select name="decision"><option value="Renewed">{c("أؤكد تجديد عضويتي","I confirm renewing my membership")}</option><option value="Declined">{c("لا أرغب بالتجديد لهذا الفصل","I do not want to renew this term")}</option></select></label><p className="text-sm leading-7 text-muted">{c("الرد النهائي محفوظ. رفض التجديد أو عدم الرد لا ينهي العضوية تلقائيًا.","Your final response is saved. Declining or not responding does not automatically end your membership.")}</p></HoursForm>}</li>)}</ul>:<p className="panel p-6 text-muted">{c("لا توجد حملات تجديد موجهة لك الآن.","No renewal campaigns are addressed to you now.")}</p>}<TaskPagination page={page} more={data.items.length>25} base="/renewals" locale={locale}/></div>;}
export function RenewalWorkspaceView({data,org,page,memberPage,locale="ar"}:{data:RenewalWorkspace;org:string;page:number;memberPage:number;locale?:Locale}){
 const base=`/manage/organizations/${org}/renewals`,campaign=data.selected;const query={...(campaign?{campaign:campaign.id}:{}),page:String(page)},en=locale==="en",c=(ar:string,english:string)=>en?english:ar,labels=en?hourLabelsEn:hourLabels,date=en?formatTaskDateEn:formatTaskDate;
 return <div className="space-y-8"><div><Link className="text-link mb-4 inline-block" href={`/manage/organizations/${org}`}>{c("إدارة الجهة","Manage organization")}</Link><h1 className="text-3xl leading-normal font-bold">{c("تجديد","Renewals for")} <bdi>{data.name}</bdi></h1><p className="mt-3 leading-8 text-muted">{c("كل حملة تخص فصلًا أكاديميًا واحدًا. العضوية الأصلية تستمر عبر الفصول.","Each campaign covers one academic term. The original membership continues across terms.")}</p></div><details className="panel p-6"><summary className="cursor-pointer font-semibold">{c("حملة تجديد جديدة","New renewal campaign")}</summary><div className="mt-5"><HoursForm operation="campaign" fields={{org}} label={c("إنشاء المسودة","Create draft")} locale={locale}><TermSelect terms={data.terms} locale={locale}/><div className="grid gap-4 sm:grid-cols-2"><DateInput name="opens" label={c("بداية استقبال الردود","Responses open")} required locale={locale}/><DateInput name="closes" label={c("إغلاق الردود","Responses close")} required locale={locale}/></div><label className="flex items-center gap-3"><input name="leaders" type="checkbox" className="size-5"/>{c("استثناء القادة والنواب من التجديد","Exclude leaders and deputies from renewal")}</label><p className="text-sm leading-7 text-muted">{c("تشمل الحملة الأعضاء النشطين عند فتحها، ويمكن إضافة استثناءات قبل الفتح.","The campaign includes active members when opened. Exceptions can be added before opening.")}</p></HoursForm></div></details>
 <section className="space-y-4"><h2 className="text-xl font-semibold">{c("الحملات","Campaigns")}</h2><ul className="grid gap-4 sm:grid-cols-2">{data.campaigns.slice(0,25).map(x=><li key={x.id} className="panel p-5"><Link dir="auto" className="text-link font-semibold" href={`${base}?campaign=${x.id}`}>{x.name}</Link><p className="mt-3 text-sm leading-7 text-muted">{campaignLabel(x,locale)} · {c("الإغلاق","closes")} {date(x.closes_at)}</p></li>)}</ul>{!data.campaigns.length&&<p className="panel p-6 text-muted">{c("لم تُنشأ حملات تجديد بعد.","No renewal campaigns have been created yet.")}</p>}<TaskPagination page={page} more={data.campaigns.length>25} base={base} locale={locale}/></section>
 {campaign&&<section className="panel space-y-6 p-6"><h2 className="text-xl font-semibold"><bdi>{campaign.name}</bdi> · {campaignLabel(campaign,locale)}</h2><p className="text-sm leading-7 text-muted">{c("من","from")} {date(campaign.opens_at)} {c("إلى","to")} {date(campaign.closes_at)}</p><p className="leading-8 text-muted">{c("الإغلاق يحفظ «لم يرد» لمن لم يجب، ويحفظ العضويات والأدوار كما هي.","Closing records no response for members who did not answer, while preserving memberships and roles.")}</p>{campaign.status_code!=="Archived"&&<HoursForm operation="campaign-status" fields={{campaign:campaign.id,status:campaign.status_code==="Draft"?"Open":campaign.status_code==="Open"?"Closed":"Archived"}} label={campaign.status_code==="Draft"?c("فتح الحملة","Open campaign"):campaign.status_code==="Open"?c("إغلاق الحملة","Close campaign"):c("أرشفة الحملة","Archive campaign")} locale={locale}><label className="flex items-center gap-3"><input type="checkbox" name="confirm" required className="size-5"/>{c("أؤكد هذا الإجراء على الحملة","I confirm this action on the campaign")}</label></HoursForm>}
 {campaign.status_code==="Draft"&&<div className="space-y-5 border-t border-line pt-5"><h3 className="font-semibold">{c("الاستثناءات","Exceptions")}</h3>{data.members.length>0&&<HoursForm operation="exclude" fields={{campaign:campaign.id,excluded:"on"}} label={c("استثناء العضو","Exclude member")} locale={locale}><label>{c("العضو","Member")}<select name="member">{data.members.slice(0,25).map(m=><option key={m.id} value={m.id} dir="auto">{m.name}</option>)}</select></label><label>{c("سبب الاستثناء","Reason for exception")}<input name="reason" required maxLength={300}/></label></HoursForm>}{data.exclusions.slice(0,25).map(e=><div key={e.id}><p dir="auto" className="mb-3 break-words">{e.name??c("عضو مستثنى","Excluded member")} · {e.reason}</p><HoursForm operation="exclude" fields={{campaign:campaign.id,member:e.id}} label={c("إزالة الاستثناء","Remove exception")} locale={locale}/></div>)}</div>}
 {campaign.status_code!=="Draft"&&<><h3 className="font-semibold">{c("نتائج التجديد","Renewal results")}</h3><ul className="flex flex-wrap gap-5">{data.counts.map(x=><li key={x.status}>{x.status==="Pending"?c("بانتظار الرد","Awaiting response"):labels[x.status]}: {x.count}</li>)}</ul><ul className="divide-y divide-line">{data.responses.slice(0,25).map(r=><li key={r.id} className="py-4 break-words"><bdi>{r.name??c("عضو","Member")}</bdi> · {r.response_code==="Pending"?c("بانتظار الرد","Awaiting response"):labels[r.response_code]}</li>)}</ul></>}
 <nav aria-label={c("صفحات أعضاء الحملة","Campaign member pages")} className="flex flex-wrap gap-4">{memberPage>0&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,memberPage:String(memberPage-1)})}`}>{c("السابق","Previous")}</Link>}{(data.responses.length>25||data.members.length>25||data.exclusions.length>25)&&<Link className="text-link" href={`${base}?${new URLSearchParams({...query,memberPage:String(memberPage+1)})}`}>{c("التالي","Next")}</Link>}</nav></section>}</div>;
}
