import {localizedMetadata} from "@/lib/localized-metadata";
import Link from "next/link";
import {notFound} from "next/navigation";
import {z} from "zod";
import {requireUser} from "@/features/auth/session";
import {checkReadiness} from "@/features/hours/view";
import {eventWorkspace} from "@/features/events/repository";
import {EventForm,EventFields} from "@/features/events/form";
import {EventGrants} from "@/features/events/view";
import {eventLabels,eventDate,eventLabelsEn,eventDateEn} from "@/features/events/display";
import {getPreferences} from "@/lib/preferences";
export async function generateMetadata(){return localizedMetadata('إدارة الفعاليات','Manage events');}
export default async function ManageEvents({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{page?:string;members?:string;grants?:string}>}){const [user,{locale}]=await Promise.all([requireUser(),getPreferences()]);const en=locale==="en",labels=en?eventLabelsEn:eventLabels,date=en?eventDateEn:eventDate;const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();const s=await searchParams;const page=Math.floor(Math.min(10000,Math.max(0,Number(s.page)||0)));const memberPage=Math.floor(Math.min(10000,Math.max(0,Number(s.members)||0))),grantPage=Math.floor(Math.min(10000,Math.max(0,Number(s.grants)||0)));const data=await eventWorkspace(user.id,id,page,memberPage,grantPage);if(!data)notFound();checkReadiness(data);return <><Link href={`/manage/organizations/${id}`} className="text-link">{en?"Manage":"إدارة"} <bdi>{data.name}</bdi></Link><h1 className="my-6 text-3xl font-bold">{en?"Events":"الفعاليات"}</h1>{data.canManage&&<details className="panel mb-6 p-6"><summary className="cursor-pointer text-xl font-semibold">{en?"New event":"فعالية جديدة"}</summary><div className="mt-5"><EventForm operation="save" fields={{org:id}} label={en?"Save draft":"حفظ مسودة"} locale={locale}><EventFields templates={data.templates} locale={locale}/></EventForm></div></details>}{data.canGrant&&<EventGrants org={id} members={data.members} grants={data.grants} memberPage={memberPage} grantPage={grantPage} page={page} locale={locale}/>}<ul className="space-y-4">{data.events.slice(0,25).map(e=><li key={e.id} className="panel p-6"><Link className="text-link font-semibold" href={`/events/${e.id}`} dir="auto">{e.title}</Link><p className="mt-3 text-muted">{labels[e.status_code]} · {date(e.starts_at)}</p></li>)}</ul>{!data.events.length&&<p className="panel p-6 text-muted">{en?"No events for this organization yet.":"لا توجد فعاليات للجهة."}</p>}<nav aria-label={en?"Event pages":"صفحات الفعاليات"} className="mt-6 flex gap-5">{page>0&&<Link className="text-link" href={`?page=${page-1}`}>{en?"Previous":"السابق"}</Link>}{data.events.length>25&&<Link className="text-link" href={`?page=${page+1}`}>{en?"Next":"التالي"}</Link>}</nav></>;}
